// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module AESL_axi_slave_BUS_A (
    clk,
    reset,
    TRAN_s_axi_BUS_A_AWADDR,
    TRAN_s_axi_BUS_A_AWVALID,
    TRAN_s_axi_BUS_A_AWREADY,
    TRAN_s_axi_BUS_A_WVALID,
    TRAN_s_axi_BUS_A_WREADY,
    TRAN_s_axi_BUS_A_WDATA,
    TRAN_s_axi_BUS_A_WSTRB,
    TRAN_s_axi_BUS_A_ARADDR,
    TRAN_s_axi_BUS_A_ARVALID,
    TRAN_s_axi_BUS_A_ARREADY,
    TRAN_s_axi_BUS_A_RVALID,
    TRAN_s_axi_BUS_A_RREADY,
    TRAN_s_axi_BUS_A_RDATA,
    TRAN_s_axi_BUS_A_RRESP,
    TRAN_s_axi_BUS_A_BVALID,
    TRAN_s_axi_BUS_A_BREADY,
    TRAN_s_axi_BUS_A_BRESP,
    TRAN_BUS_A_write_data_finish,
    TRAN_BUS_A_read_data_finish,
    TRAN_BUS_A_start_in,
    TRAN_BUS_A_idle_out,
    TRAN_BUS_A_ready_out,
    TRAN_BUS_A_ready_in,
    TRAN_BUS_A_done_out,
    TRAN_BUS_A_write_start_in   ,
    TRAN_BUS_A_write_start_finish,
    TRAN_BUS_A_interrupt,
    TRAN_BUS_A_transaction_done_in
    );

//------------------------Parameter----------------------
`define TV_IN_config_init "./c.DuneDataCompressionCore.autotvin_config_init.dat"
`define TV_IN_config_mode "./c.DuneDataCompressionCore.autotvin_config_mode.dat"
`define TV_IN_config_limit "./c.DuneDataCompressionCore.autotvin_config_limit.dat"
`define TV_OUT_monitor_common_pattern "./rtl.DuneDataCompressionCore.autotvout_monitor_common_pattern.dat"
`define TV_OUT_monitor_cfg_m_mode "./rtl.DuneDataCompressionCore.autotvout_monitor_cfg_m_mode.dat"
`define TV_OUT_monitor_cfg_m_ncfgs "./rtl.DuneDataCompressionCore.autotvout_monitor_cfg_m_ncfgs.dat"
`define TV_OUT_monitor_write_nbytes "./rtl.DuneDataCompressionCore.autotvout_monitor_write_nbytes.dat"
`define TV_OUT_monitor_write_npromoted "./rtl.DuneDataCompressionCore.autotvout_monitor_write_npromoted.dat"
`define TV_OUT_monitor_write_ndropped "./rtl.DuneDataCompressionCore.autotvout_monitor_write_ndropped.dat"
`define TV_OUT_monitor_write_npackets "./rtl.DuneDataCompressionCore.autotvout_monitor_write_npackets.dat"
parameter ADDR_WIDTH = 10;
parameter DATA_WIDTH = 32;
parameter config_init_DEPTH = 1;
reg [31 : 0] config_init_OPERATE_DEPTH = 0;
parameter config_init_c_bitwidth = 32;
parameter config_mode_DEPTH = 1;
reg [31 : 0] config_mode_OPERATE_DEPTH = 0;
parameter config_mode_c_bitwidth = 32;
parameter config_limit_DEPTH = 1;
reg [31 : 0] config_limit_OPERATE_DEPTH = 0;
parameter config_limit_c_bitwidth = 32;
parameter monitor_common_pattern_DEPTH = 1;
reg [31 : 0] monitor_common_pattern_OPERATE_DEPTH = 0;
parameter monitor_common_pattern_c_bitwidth = 32;
parameter monitor_cfg_m_mode_DEPTH = 1;
reg [31 : 0] monitor_cfg_m_mode_OPERATE_DEPTH = 0;
parameter monitor_cfg_m_mode_c_bitwidth = 32;
parameter monitor_cfg_m_ncfgs_DEPTH = 1;
reg [31 : 0] monitor_cfg_m_ncfgs_OPERATE_DEPTH = 0;
parameter monitor_cfg_m_ncfgs_c_bitwidth = 32;
parameter monitor_write_nbytes_DEPTH = 1;
reg [31 : 0] monitor_write_nbytes_OPERATE_DEPTH = 0;
parameter monitor_write_nbytes_c_bitwidth = 32;
parameter monitor_write_npromoted_DEPTH = 1;
reg [31 : 0] monitor_write_npromoted_OPERATE_DEPTH = 0;
parameter monitor_write_npromoted_c_bitwidth = 32;
parameter monitor_write_ndropped_DEPTH = 1;
reg [31 : 0] monitor_write_ndropped_OPERATE_DEPTH = 0;
parameter monitor_write_ndropped_c_bitwidth = 32;
parameter monitor_write_npackets_DEPTH = 1;
reg [31 : 0] monitor_write_npackets_OPERATE_DEPTH = 0;
parameter monitor_write_npackets_c_bitwidth = 32;
parameter START_ADDR = 0;
parameter DuneDataCompressionCore_continue_addr = 0;
parameter DuneDataCompressionCore_auto_start_addr = 0;
parameter config_init_data_in_addr = 16;
parameter config_mode_data_in_addr = 24;
parameter config_limit_data_in_addr = 32;
parameter config_chns_disabled_data_in_addr = 128;
parameter monitor_read_summary_mask_V_data_in_addr = 280;
parameter monitor_read_summary_nframes_data_in_addr = 288;
parameter monitor_read_summary_nStates_data_in_addr = 304;
parameter monitor_read_errs_nFrameErrs_data_in_addr = 320;
parameter monitor_read_errs_nWibErrs_data_in_addr = 384;
parameter config_chns_disabled_data_out_addr = 128;
parameter monitor_common_pattern_data_out_addr = 256;
parameter monitor_common_pattern_valid_out_addr = 260;
parameter monitor_cfg_m_mode_data_out_addr = 264;
parameter monitor_cfg_m_mode_valid_out_addr = 268;
parameter monitor_cfg_m_ncfgs_data_out_addr = 272;
parameter monitor_cfg_m_ncfgs_valid_out_addr = 276;
parameter monitor_read_summary_nStates_data_out_addr = 304;
parameter monitor_read_errs_nFrameErrs_data_out_addr = 320;
parameter monitor_read_errs_nWibErrs_data_out_addr = 384;
parameter monitor_write_nbytes_data_out_addr = 512;
parameter monitor_write_nbytes_valid_out_addr = 516;
parameter monitor_write_npromoted_data_out_addr = 520;
parameter monitor_write_npromoted_valid_out_addr = 524;
parameter monitor_write_ndropped_data_out_addr = 528;
parameter monitor_write_ndropped_valid_out_addr = 532;
parameter monitor_write_npackets_data_out_addr = 536;
parameter monitor_write_npackets_valid_out_addr = 540;
parameter STATUS_ADDR = 0;

output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_BUS_A_AWADDR;
output  TRAN_s_axi_BUS_A_AWVALID;
input  TRAN_s_axi_BUS_A_AWREADY;
output  TRAN_s_axi_BUS_A_WVALID;
input  TRAN_s_axi_BUS_A_WREADY;
output [DATA_WIDTH - 1 : 0] TRAN_s_axi_BUS_A_WDATA;
output [DATA_WIDTH/8 - 1 : 0] TRAN_s_axi_BUS_A_WSTRB;
output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_BUS_A_ARADDR;
output  TRAN_s_axi_BUS_A_ARVALID;
input  TRAN_s_axi_BUS_A_ARREADY;
input  TRAN_s_axi_BUS_A_RVALID;
output  TRAN_s_axi_BUS_A_RREADY;
input [DATA_WIDTH - 1 : 0] TRAN_s_axi_BUS_A_RDATA;
input [2 - 1 : 0] TRAN_s_axi_BUS_A_RRESP;
input  TRAN_s_axi_BUS_A_BVALID;
output  TRAN_s_axi_BUS_A_BREADY;
input [2 - 1 : 0] TRAN_s_axi_BUS_A_BRESP;
output TRAN_BUS_A_write_data_finish;
output TRAN_BUS_A_read_data_finish;
input     clk;
input     reset;
input     TRAN_BUS_A_start_in;
output    TRAN_BUS_A_done_out;
output    TRAN_BUS_A_ready_out;
input     TRAN_BUS_A_ready_in;
output    TRAN_BUS_A_idle_out;
input  TRAN_BUS_A_write_start_in   ;
output TRAN_BUS_A_write_start_finish;
input     TRAN_BUS_A_interrupt;
input     TRAN_BUS_A_transaction_done_in;

reg [ADDR_WIDTH - 1 : 0] AWADDR_reg = 0;
reg  AWVALID_reg = 0;
reg  WVALID_reg = 0;
reg [DATA_WIDTH - 1 : 0] WDATA_reg = 0;
reg [DATA_WIDTH/8 - 1 : 0] WSTRB_reg = 0;
reg [ADDR_WIDTH - 1 : 0] ARADDR_reg = 0;
reg  ARVALID_reg = 0;
reg  RREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] RDATA_reg = 0;
reg  BREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] mem_config_init [config_init_DEPTH - 1 : 0];
reg config_init_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_config_mode [config_mode_DEPTH - 1 : 0];
reg config_mode_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_config_limit [config_limit_DEPTH - 1 : 0];
reg config_limit_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_common_pattern [monitor_common_pattern_DEPTH - 1 : 0];
reg monitor_common_pattern_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_cfg_m_mode [monitor_cfg_m_mode_DEPTH - 1 : 0];
reg monitor_cfg_m_mode_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_cfg_m_ncfgs [monitor_cfg_m_ncfgs_DEPTH - 1 : 0];
reg monitor_cfg_m_ncfgs_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_write_nbytes [monitor_write_nbytes_DEPTH - 1 : 0];
reg monitor_write_nbytes_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_write_npromoted [monitor_write_npromoted_DEPTH - 1 : 0];
reg monitor_write_npromoted_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_write_ndropped [monitor_write_ndropped_DEPTH - 1 : 0];
reg monitor_write_ndropped_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_monitor_write_npackets [monitor_write_npackets_DEPTH - 1 : 0];
reg monitor_write_npackets_read_data_finish;
reg AESL_ready_out_index_reg = 0;
reg AESL_write_start_finish = 0;
reg AESL_ready_reg;
reg ready_initial;
reg AESL_done_index_reg = 0;
reg AESL_idle_index_reg = 0;
reg AESL_auto_restart_index_reg;
reg process_0_finish = 0;
reg process_1_finish = 0;
reg process_2_finish = 0;
reg process_3_finish = 0;
reg process_4_finish = 0;
reg process_5_finish = 0;
reg process_6_finish = 0;
reg process_7_finish = 0;
reg process_8_finish = 0;
reg process_9_finish = 0;
reg process_10_finish = 0;
reg process_11_finish = 0;
//write config_init reg
reg [31 : 0] write_config_init_count = 0;
reg write_config_init_run_flag = 0;
reg write_one_config_init_data_done = 0;
//write config_mode reg
reg [31 : 0] write_config_mode_count = 0;
reg write_config_mode_run_flag = 0;
reg write_one_config_mode_data_done = 0;
//write config_limit reg
reg [31 : 0] write_config_limit_count = 0;
reg write_config_limit_run_flag = 0;
reg write_one_config_limit_data_done = 0;
//read monitor_common_pattern reg
reg [31 : 0] read_monitor_common_pattern_count = 0;
reg read_monitor_common_pattern_run_flag = 0;
reg read_one_monitor_common_pattern_data_done = 0;
//read monitor_cfg_m_mode reg
reg [31 : 0] read_monitor_cfg_m_mode_count = 0;
reg read_monitor_cfg_m_mode_run_flag = 0;
reg read_one_monitor_cfg_m_mode_data_done = 0;
//read monitor_cfg_m_ncfgs reg
reg [31 : 0] read_monitor_cfg_m_ncfgs_count = 0;
reg read_monitor_cfg_m_ncfgs_run_flag = 0;
reg read_one_monitor_cfg_m_ncfgs_data_done = 0;
//read monitor_write_nbytes reg
reg [31 : 0] read_monitor_write_nbytes_count = 0;
reg read_monitor_write_nbytes_run_flag = 0;
reg read_one_monitor_write_nbytes_data_done = 0;
//read monitor_write_npromoted reg
reg [31 : 0] read_monitor_write_npromoted_count = 0;
reg read_monitor_write_npromoted_run_flag = 0;
reg read_one_monitor_write_npromoted_data_done = 0;
//read monitor_write_ndropped reg
reg [31 : 0] read_monitor_write_ndropped_count = 0;
reg read_monitor_write_ndropped_run_flag = 0;
reg read_one_monitor_write_ndropped_data_done = 0;
//read monitor_write_npackets reg
reg [31 : 0] read_monitor_write_npackets_count = 0;
reg read_monitor_write_npackets_run_flag = 0;
reg read_one_monitor_write_npackets_data_done = 0;
reg [31 : 0] write_start_count = 0;
reg write_start_run_flag = 0;

//===================process control=================
reg [31 : 0] ongoing_process_number = 0;
//process number depends on how much processes needed.
reg process_busy = 0;

//=================== signal connection ==============
assign TRAN_s_axi_BUS_A_AWADDR = AWADDR_reg;
assign TRAN_s_axi_BUS_A_AWVALID = AWVALID_reg;
assign TRAN_s_axi_BUS_A_WVALID = WVALID_reg;
assign TRAN_s_axi_BUS_A_WDATA = WDATA_reg;
assign TRAN_s_axi_BUS_A_WSTRB = WSTRB_reg;
assign TRAN_s_axi_BUS_A_ARADDR = ARADDR_reg;
assign TRAN_s_axi_BUS_A_ARVALID = ARVALID_reg;
assign TRAN_s_axi_BUS_A_RREADY = RREADY_reg;
assign TRAN_s_axi_BUS_A_BREADY = BREADY_reg;
assign TRAN_BUS_A_write_start_finish = AESL_write_start_finish;
assign TRAN_BUS_A_done_out = AESL_done_index_reg;
assign TRAN_BUS_A_ready_out = AESL_ready_out_index_reg;
assign TRAN_BUS_A_idle_out = AESL_idle_index_reg;
assign TRAN_BUS_A_read_data_finish = 1 & monitor_common_pattern_read_data_finish & monitor_cfg_m_mode_read_data_finish & monitor_cfg_m_ncfgs_read_data_finish & monitor_write_nbytes_read_data_finish & monitor_write_npromoted_read_data_finish & monitor_write_ndropped_read_data_finish & monitor_write_npackets_read_data_finish;
assign TRAN_BUS_A_write_data_finish = 1 & config_init_write_data_finish & config_mode_write_data_finish & config_limit_write_data_finish;
always @(TRAN_BUS_A_ready_in or ready_initial) 
begin
    AESL_ready_reg <= TRAN_BUS_A_ready_in | ready_initial;
end

always @(reset or process_0_finish or process_1_finish or process_2_finish or process_3_finish or process_4_finish or process_5_finish or process_6_finish or process_7_finish or process_8_finish or process_9_finish or process_10_finish or process_11_finish ) begin
    if (reset == 0) begin
        ongoing_process_number <= 0;
    end
    else if (ongoing_process_number == 0 && process_0_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 1 && process_1_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 2 && process_2_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 3 && process_3_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 4 && process_4_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 5 && process_5_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 6 && process_6_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 7 && process_7_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 8 && process_8_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 9 && process_9_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 10 && process_10_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 11 && process_11_finish == 1) begin
            ongoing_process_number <= 0;
    end
end

task count_c_data_four_byte_num_by_bitwidth;
input  integer bitwidth;
output integer num;
integer factor;
integer i;
begin
    factor = 32;
    for (i = 1; i <= 32; i = i + 1) begin
        if (bitwidth <= factor && bitwidth > factor - 32) begin
            num = i;
        end
        factor = factor + 32;
    end
end    
endtask

task count_seperate_factor_by_bitwidth;
input  integer bitwidth;
output integer factor;
begin
    if (bitwidth <= 8 ) begin
        factor=4;
    end
    if (bitwidth <= 16 & bitwidth > 8 ) begin
        factor=2;
    end
    if (bitwidth <= 32 & bitwidth > 16 ) begin
        factor=1;
    end
    if (bitwidth <= 1024 & bitwidth > 32 ) begin
        factor=1;
    end
end    
endtask

task count_operate_depth_by_bitwidth_and_depth;
input  integer bitwidth;
input  integer depth;
output integer operate_depth;
integer factor;
integer remain;
begin
    count_seperate_factor_by_bitwidth (bitwidth , factor);
    operate_depth = depth / factor;
    remain = depth % factor;
    if (remain > 0) begin
        operate_depth = operate_depth + 1;
    end
end    
endtask

task write; /*{{{*/
    input  reg [ADDR_WIDTH - 1:0] waddr;   // write address
    input  reg [DATA_WIDTH - 1:0] wdata;   // write data
    output reg wresp;
    reg aw_flag;
    reg w_flag;
    reg [DATA_WIDTH/8 - 1:0] wstrb_reg;
    integer i;
begin 
    wresp = 0;
    aw_flag = 0;
    w_flag = 0;
//=======================one single write operate======================
    AWADDR_reg <= waddr;
    AWVALID_reg <= 1;
    WDATA_reg <= wdata;
    WVALID_reg <= 1;
    for (i = 0; i < DATA_WIDTH/8; i = i + 1) begin
        wstrb_reg [i] = 1;
    end    
    WSTRB_reg <= wstrb_reg;
    while (!(aw_flag && w_flag)) begin
        @(posedge clk);
        if (aw_flag != 1)
            aw_flag = TRAN_s_axi_BUS_A_AWREADY & AWVALID_reg;
        if (w_flag != 1)
            w_flag = TRAN_s_axi_BUS_A_WREADY & WVALID_reg;
        AWVALID_reg <= !aw_flag;
        WVALID_reg <= !w_flag;
    end

    BREADY_reg <= 1;
    while (TRAN_s_axi_BUS_A_BVALID != 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    BREADY_reg <= 0;
    if (TRAN_s_axi_BUS_A_BRESP === 2'b00) begin
        wresp = 1;
        //input success. in fact BRESP is always 2'b00
    end   
//=======================one single write operate======================

end
endtask/*}}}*/

task read (/*{{{*/
    input  [ADDR_WIDTH - 1:0] raddr ,   // write address
    output [DATA_WIDTH - 1:0] RDATA_result ,
    output rresp
);
begin 
    rresp = 0;
//=======================one single read operate======================
    ARADDR_reg <= raddr;
    ARVALID_reg <= 1;
    while (TRAN_s_axi_BUS_A_ARREADY !== 1) begin
        @(posedge clk);
    end
    @(posedge clk);
    ARVALID_reg <= 0;
    RREADY_reg <= 1;
    while (TRAN_s_axi_BUS_A_RVALID !== 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    RDATA_result  <= TRAN_s_axi_BUS_A_RDATA;
    RREADY_reg <= 0;
    if (TRAN_s_axi_BUS_A_RRESP === 2'b00 ) begin
        rresp <= 1;
        //output success. in fact RRESP is always 2'b00
    end  
    @(posedge clk);

//=======================one single read operate end======================

end
endtask/*}}}*/

initial begin : ready_initial_process
    ready_initial = 0;
    wait(reset === 1);
    @(posedge clk);
    ready_initial = 1;
    @(posedge clk);
    ready_initial = 0;
end

initial begin : update_status
    integer process_num ;
    integer read_status_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 0;
    while (1) begin
        process_0_finish = 0;
        AESL_done_index_reg         <= 0;
        AESL_ready_out_index_reg        <= 0;
        if (ongoing_process_number === process_num && process_busy === 0) begin
            process_busy = 1;
            read (STATUS_ADDR, RDATA_reg, read_status_resp);
                AESL_done_index_reg         <= RDATA_reg[1 : 1];
                AESL_ready_out_index_reg    <= RDATA_reg[1 : 1];
                AESL_idle_index_reg         <= RDATA_reg[2 : 2];
            process_0_finish = 1;
            process_busy = 0;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        config_init_write_data_finish <= 0;
        write_config_init_run_flag <= 0; 
        write_config_init_count = 0;
        count_operate_depth_by_bitwidth_and_depth (config_init_c_bitwidth, config_init_DEPTH, config_init_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            config_init_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_config_init_run_flag <= 1; 
            write_config_init_count = 0;
        end
        if (write_one_config_init_data_done === 1) begin
            write_config_init_count = write_config_init_count + 1;
            if (write_config_init_count == config_init_OPERATE_DEPTH) begin
                write_config_init_run_flag <= 0; 
                config_init_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_config_init
    integer write_config_init_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] config_init_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = config_init_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_config_init_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write config_init data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (config_init_c_bitwidth < 32) begin
                        config_init_data_tmp_reg = mem_config_init[write_config_init_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < config_init_c_bitwidth) begin
                                config_init_data_tmp_reg[j] = mem_config_init[write_config_init_count][i*32 + j];
                            end
                            else begin
                                config_init_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (config_init_data_in_addr + write_config_init_count * four_byte_num * 4 + i * 4, config_init_data_tmp_reg, write_config_init_resp);
                end
                process_busy = 0;
                write_one_config_init_data_done <= 1;
                @(posedge clk);
                write_one_config_init_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        config_mode_write_data_finish <= 0;
        write_config_mode_run_flag <= 0; 
        write_config_mode_count = 0;
        count_operate_depth_by_bitwidth_and_depth (config_mode_c_bitwidth, config_mode_DEPTH, config_mode_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            config_mode_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_config_mode_run_flag <= 1; 
            write_config_mode_count = 0;
        end
        if (write_one_config_mode_data_done === 1) begin
            write_config_mode_count = write_config_mode_count + 1;
            if (write_config_mode_count == config_mode_OPERATE_DEPTH) begin
                write_config_mode_run_flag <= 0; 
                config_mode_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_config_mode
    integer write_config_mode_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] config_mode_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = config_mode_c_bitwidth;
    process_num = 2;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_2_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_config_mode_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write config_mode data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (config_mode_c_bitwidth < 32) begin
                        config_mode_data_tmp_reg = mem_config_mode[write_config_mode_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < config_mode_c_bitwidth) begin
                                config_mode_data_tmp_reg[j] = mem_config_mode[write_config_mode_count][i*32 + j];
                            end
                            else begin
                                config_mode_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (config_mode_data_in_addr + write_config_mode_count * four_byte_num * 4 + i * 4, config_mode_data_tmp_reg, write_config_mode_resp);
                end
                process_busy = 0;
                write_one_config_mode_data_done <= 1;
                @(posedge clk);
                write_one_config_mode_data_done <= 0;
            end   
            process_2_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        config_limit_write_data_finish <= 0;
        write_config_limit_run_flag <= 0; 
        write_config_limit_count = 0;
        count_operate_depth_by_bitwidth_and_depth (config_limit_c_bitwidth, config_limit_DEPTH, config_limit_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            config_limit_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_config_limit_run_flag <= 1; 
            write_config_limit_count = 0;
        end
        if (write_one_config_limit_data_done === 1) begin
            write_config_limit_count = write_config_limit_count + 1;
            if (write_config_limit_count == config_limit_OPERATE_DEPTH) begin
                write_config_limit_run_flag <= 0; 
                config_limit_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_config_limit
    integer write_config_limit_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] config_limit_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = config_limit_c_bitwidth;
    process_num = 3;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_3_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_config_limit_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write config_limit data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (config_limit_c_bitwidth < 32) begin
                        config_limit_data_tmp_reg = mem_config_limit[write_config_limit_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < config_limit_c_bitwidth) begin
                                config_limit_data_tmp_reg[j] = mem_config_limit[write_config_limit_count][i*32 + j];
                            end
                            else begin
                                config_limit_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (config_limit_data_in_addr + write_config_limit_count * four_byte_num * 4 + i * 4, config_limit_data_tmp_reg, write_config_limit_resp);
                end
                process_busy = 0;
                write_one_config_limit_data_done <= 1;
                @(posedge clk);
                write_one_config_limit_data_done <= 0;
            end   
            process_3_finish <= 1;
        end
        @(posedge clk);
    end    
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_start_run_flag <= 0; 
        write_start_count <= 0;
    end
    else begin
        if (write_start_count >= 1) begin
            write_start_run_flag <= 0; 
        end
        else if (TRAN_BUS_A_write_start_in === 1) begin
            write_start_run_flag <= 1; 
        end
        if (AESL_write_start_finish === 1) begin
            write_start_count <= write_start_count + 1;
            write_start_run_flag <= 0; 
        end
    end
end

initial begin : write_start
    reg [DATA_WIDTH - 1 : 0] write_start_tmp;
    integer process_num;
    integer write_start_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 4;
    while (1) begin
        process_4_finish = 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (write_start_run_flag === 1) begin
                process_busy = 1;
                write_start_tmp=0;
                write_start_tmp[0 : 0] = 1;
                write (START_ADDR, write_start_tmp, write_start_resp);
                process_busy = 0;
                AESL_write_start_finish <= 1;
                @(posedge clk);
                AESL_write_start_finish <= 0;
            end
            process_4_finish <= 1;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_common_pattern_read_data_finish <= 0;
        read_monitor_common_pattern_run_flag <= 0; 
        read_monitor_common_pattern_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_common_pattern_c_bitwidth, monitor_common_pattern_DEPTH, monitor_common_pattern_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_common_pattern_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_common_pattern_read_data_finish <= 0;
            read_monitor_common_pattern_count = 0; 
        end
        if (read_one_monitor_common_pattern_data_done === 1) begin
            read_monitor_common_pattern_count = read_monitor_common_pattern_count + 1;
            if (read_monitor_common_pattern_count == monitor_common_pattern_OPERATE_DEPTH) begin
                read_monitor_common_pattern_run_flag <= 0; 
                monitor_common_pattern_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_common_pattern
    integer read_monitor_common_pattern_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_common_pattern_c_bitwidth;
    process_num = 5;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_5_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_common_pattern_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_common_pattern vld
                read (monitor_common_pattern_valid_out_addr, RDATA_reg, read_monitor_common_pattern_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_common_pattern data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_common_pattern_data_out_addr + read_monitor_common_pattern_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_common_pattern_resp);
                        if (monitor_common_pattern_c_bitwidth < 32) begin
                            mem_monitor_common_pattern[read_monitor_common_pattern_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_common_pattern_c_bitwidth) begin
                                    mem_monitor_common_pattern[read_monitor_common_pattern_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_common_pattern_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_common_pattern_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_5_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_cfg_m_mode_read_data_finish <= 0;
        read_monitor_cfg_m_mode_run_flag <= 0; 
        read_monitor_cfg_m_mode_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_cfg_m_mode_c_bitwidth, monitor_cfg_m_mode_DEPTH, monitor_cfg_m_mode_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_cfg_m_mode_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_cfg_m_mode_read_data_finish <= 0;
            read_monitor_cfg_m_mode_count = 0; 
        end
        if (read_one_monitor_cfg_m_mode_data_done === 1) begin
            read_monitor_cfg_m_mode_count = read_monitor_cfg_m_mode_count + 1;
            if (read_monitor_cfg_m_mode_count == monitor_cfg_m_mode_OPERATE_DEPTH) begin
                read_monitor_cfg_m_mode_run_flag <= 0; 
                monitor_cfg_m_mode_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_cfg_m_mode
    integer read_monitor_cfg_m_mode_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_cfg_m_mode_c_bitwidth;
    process_num = 6;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_6_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_cfg_m_mode_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_cfg_m_mode vld
                read (monitor_cfg_m_mode_valid_out_addr, RDATA_reg, read_monitor_cfg_m_mode_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_cfg_m_mode data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_cfg_m_mode_data_out_addr + read_monitor_cfg_m_mode_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_cfg_m_mode_resp);
                        if (monitor_cfg_m_mode_c_bitwidth < 32) begin
                            mem_monitor_cfg_m_mode[read_monitor_cfg_m_mode_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_cfg_m_mode_c_bitwidth) begin
                                    mem_monitor_cfg_m_mode[read_monitor_cfg_m_mode_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_cfg_m_mode_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_cfg_m_mode_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_6_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_cfg_m_ncfgs_read_data_finish <= 0;
        read_monitor_cfg_m_ncfgs_run_flag <= 0; 
        read_monitor_cfg_m_ncfgs_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_cfg_m_ncfgs_c_bitwidth, monitor_cfg_m_ncfgs_DEPTH, monitor_cfg_m_ncfgs_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_cfg_m_ncfgs_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_cfg_m_ncfgs_read_data_finish <= 0;
            read_monitor_cfg_m_ncfgs_count = 0; 
        end
        if (read_one_monitor_cfg_m_ncfgs_data_done === 1) begin
            read_monitor_cfg_m_ncfgs_count = read_monitor_cfg_m_ncfgs_count + 1;
            if (read_monitor_cfg_m_ncfgs_count == monitor_cfg_m_ncfgs_OPERATE_DEPTH) begin
                read_monitor_cfg_m_ncfgs_run_flag <= 0; 
                monitor_cfg_m_ncfgs_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_cfg_m_ncfgs
    integer read_monitor_cfg_m_ncfgs_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_cfg_m_ncfgs_c_bitwidth;
    process_num = 7;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_7_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_cfg_m_ncfgs_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_cfg_m_ncfgs vld
                read (monitor_cfg_m_ncfgs_valid_out_addr, RDATA_reg, read_monitor_cfg_m_ncfgs_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_cfg_m_ncfgs data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_cfg_m_ncfgs_data_out_addr + read_monitor_cfg_m_ncfgs_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_cfg_m_ncfgs_resp);
                        if (monitor_cfg_m_ncfgs_c_bitwidth < 32) begin
                            mem_monitor_cfg_m_ncfgs[read_monitor_cfg_m_ncfgs_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_cfg_m_ncfgs_c_bitwidth) begin
                                    mem_monitor_cfg_m_ncfgs[read_monitor_cfg_m_ncfgs_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_cfg_m_ncfgs_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_cfg_m_ncfgs_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_7_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_write_nbytes_read_data_finish <= 0;
        read_monitor_write_nbytes_run_flag <= 0; 
        read_monitor_write_nbytes_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_write_nbytes_c_bitwidth, monitor_write_nbytes_DEPTH, monitor_write_nbytes_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_write_nbytes_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_write_nbytes_read_data_finish <= 0;
            read_monitor_write_nbytes_count = 0; 
        end
        if (read_one_monitor_write_nbytes_data_done === 1) begin
            read_monitor_write_nbytes_count = read_monitor_write_nbytes_count + 1;
            if (read_monitor_write_nbytes_count == monitor_write_nbytes_OPERATE_DEPTH) begin
                read_monitor_write_nbytes_run_flag <= 0; 
                monitor_write_nbytes_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_write_nbytes
    integer read_monitor_write_nbytes_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_write_nbytes_c_bitwidth;
    process_num = 8;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_8_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_write_nbytes_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_write_nbytes vld
                read (monitor_write_nbytes_valid_out_addr, RDATA_reg, read_monitor_write_nbytes_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_write_nbytes data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_write_nbytes_data_out_addr + read_monitor_write_nbytes_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_write_nbytes_resp);
                        if (monitor_write_nbytes_c_bitwidth < 32) begin
                            mem_monitor_write_nbytes[read_monitor_write_nbytes_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_write_nbytes_c_bitwidth) begin
                                    mem_monitor_write_nbytes[read_monitor_write_nbytes_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_write_nbytes_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_write_nbytes_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_8_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_write_npromoted_read_data_finish <= 0;
        read_monitor_write_npromoted_run_flag <= 0; 
        read_monitor_write_npromoted_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_write_npromoted_c_bitwidth, monitor_write_npromoted_DEPTH, monitor_write_npromoted_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_write_npromoted_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_write_npromoted_read_data_finish <= 0;
            read_monitor_write_npromoted_count = 0; 
        end
        if (read_one_monitor_write_npromoted_data_done === 1) begin
            read_monitor_write_npromoted_count = read_monitor_write_npromoted_count + 1;
            if (read_monitor_write_npromoted_count == monitor_write_npromoted_OPERATE_DEPTH) begin
                read_monitor_write_npromoted_run_flag <= 0; 
                monitor_write_npromoted_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_write_npromoted
    integer read_monitor_write_npromoted_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_write_npromoted_c_bitwidth;
    process_num = 9;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_9_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_write_npromoted_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_write_npromoted vld
                read (monitor_write_npromoted_valid_out_addr, RDATA_reg, read_monitor_write_npromoted_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_write_npromoted data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_write_npromoted_data_out_addr + read_monitor_write_npromoted_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_write_npromoted_resp);
                        if (monitor_write_npromoted_c_bitwidth < 32) begin
                            mem_monitor_write_npromoted[read_monitor_write_npromoted_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_write_npromoted_c_bitwidth) begin
                                    mem_monitor_write_npromoted[read_monitor_write_npromoted_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_write_npromoted_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_write_npromoted_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_9_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_write_ndropped_read_data_finish <= 0;
        read_monitor_write_ndropped_run_flag <= 0; 
        read_monitor_write_ndropped_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_write_ndropped_c_bitwidth, monitor_write_ndropped_DEPTH, monitor_write_ndropped_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_write_ndropped_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_write_ndropped_read_data_finish <= 0;
            read_monitor_write_ndropped_count = 0; 
        end
        if (read_one_monitor_write_ndropped_data_done === 1) begin
            read_monitor_write_ndropped_count = read_monitor_write_ndropped_count + 1;
            if (read_monitor_write_ndropped_count == monitor_write_ndropped_OPERATE_DEPTH) begin
                read_monitor_write_ndropped_run_flag <= 0; 
                monitor_write_ndropped_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_write_ndropped
    integer read_monitor_write_ndropped_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_write_ndropped_c_bitwidth;
    process_num = 10;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_10_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_write_ndropped_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_write_ndropped vld
                read (monitor_write_ndropped_valid_out_addr, RDATA_reg, read_monitor_write_ndropped_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_write_ndropped data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_write_ndropped_data_out_addr + read_monitor_write_ndropped_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_write_ndropped_resp);
                        if (monitor_write_ndropped_c_bitwidth < 32) begin
                            mem_monitor_write_ndropped[read_monitor_write_ndropped_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_write_ndropped_c_bitwidth) begin
                                    mem_monitor_write_ndropped[read_monitor_write_ndropped_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_write_ndropped_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_write_ndropped_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_10_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        monitor_write_npackets_read_data_finish <= 0;
        read_monitor_write_npackets_run_flag <= 0; 
        read_monitor_write_npackets_count = 0;
        count_operate_depth_by_bitwidth_and_depth (monitor_write_npackets_c_bitwidth, monitor_write_npackets_DEPTH, monitor_write_npackets_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_BUS_A_start_in === 1) begin
            read_monitor_write_npackets_run_flag = 1; 
        end
        if (TRAN_BUS_A_transaction_done_in === 1) begin
            monitor_write_npackets_read_data_finish <= 0;
            read_monitor_write_npackets_count = 0; 
        end
        if (read_one_monitor_write_npackets_data_done === 1) begin
            read_monitor_write_npackets_count = read_monitor_write_npackets_count + 1;
            if (read_monitor_write_npackets_count == monitor_write_npackets_OPERATE_DEPTH) begin
                read_monitor_write_npackets_run_flag <= 0; 
                monitor_write_npackets_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_monitor_write_npackets
    integer read_monitor_write_npackets_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = monitor_write_npackets_c_bitwidth;
    process_num = 11;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_11_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_monitor_write_npackets_run_flag === 1) begin
                process_busy = 1;
                get_vld = 0;
                //read monitor_write_npackets vld
                read (monitor_write_npackets_valid_out_addr, RDATA_reg, read_monitor_write_npackets_resp);
                if (RDATA_reg[0 : 0] == 1) begin
                    get_vld = 1;
                end
                if (get_vld == 1) begin
                    //read monitor_write_npackets data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (monitor_write_npackets_data_out_addr + read_monitor_write_npackets_count * four_byte_num * 4 + i * 4, RDATA_reg, read_monitor_write_npackets_resp);
                        if (monitor_write_npackets_c_bitwidth < 32) begin
                            mem_monitor_write_npackets[read_monitor_write_npackets_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < monitor_write_npackets_c_bitwidth) begin
                                    mem_monitor_write_npackets[read_monitor_write_npackets_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_monitor_write_npackets_data_done <= 1;
                    @(posedge clk);
                    read_one_monitor_write_npackets_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_11_finish <= 1;
        end
        @(posedge clk);
    end    
end
//------------------------Task and function-------------- 
task read_token; 
    input integer fp; 
    output reg [127 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end 
endtask 
 
task rm_0x;
    inout reg [127 : 0] token;
    reg [127 : 0] token_tmp;
    integer idx;
    reg done;
    begin
      token_tmp = "";
      idx = 0;
       while (token[15 : 0] != "0x") begin
          token_tmp = (token[7:0] << 8*idx) | token_tmp;
          idx = idx + 1;
          token = token >> 8;
       end
       token = "";
       token = token_tmp;
     end
endtask
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_config_init_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [config_init_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (config_init_c_bitwidth , factor);
  fp = $fopen(`TV_IN_config_init ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_config_init); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < config_init_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          rm_0x(token);
          ret = $sscanf(token, "%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_config_init [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_config_init [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_config_init [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_config_init [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_config_init [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_config_mode_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [config_mode_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (config_mode_c_bitwidth , factor);
  fp = $fopen(`TV_IN_config_mode ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_config_mode); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < config_mode_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          rm_0x(token);
          ret = $sscanf(token, "%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_config_mode [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_config_mode [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_config_mode [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_config_mode [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_config_mode [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_config_limit_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [config_limit_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (config_limit_c_bitwidth , factor);
  fp = $fopen(`TV_IN_config_limit ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_config_limit); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < config_limit_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          rm_0x(token);
          ret = $sscanf(token, "%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_config_limit [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_config_limit [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_config_limit [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_config_limit [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_config_limit [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_common_pattern_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_common_pattern_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_common_pattern_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_common_pattern_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_common_pattern, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_common_pattern); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_common_pattern_DEPTH - monitor_common_pattern_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_common_pattern[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_common_pattern[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_common_pattern[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_common_pattern[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_common_pattern[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_common_pattern[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_common_pattern_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][23:16]);
          end
          if ((monitor_common_pattern_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][15:8]);
          end
          if ((monitor_common_pattern_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_common_pattern_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_common_pattern[monitor_common_pattern_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_cfg_m_mode_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_cfg_m_mode_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_cfg_m_mode_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_cfg_m_mode_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_cfg_m_mode, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_cfg_m_mode); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_cfg_m_mode_DEPTH - monitor_cfg_m_mode_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_cfg_m_mode[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_cfg_m_mode[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_cfg_m_mode[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_cfg_m_mode[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_cfg_m_mode[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_cfg_m_mode[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_cfg_m_mode_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][23:16]);
          end
          if ((monitor_cfg_m_mode_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][15:8]);
          end
          if ((monitor_cfg_m_mode_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_cfg_m_mode_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_mode[monitor_cfg_m_mode_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_cfg_m_ncfgs_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_cfg_m_ncfgs_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_cfg_m_ncfgs_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_cfg_m_ncfgs_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_cfg_m_ncfgs, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_cfg_m_ncfgs); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_cfg_m_ncfgs_DEPTH - monitor_cfg_m_ncfgs_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_cfg_m_ncfgs[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_cfg_m_ncfgs[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_cfg_m_ncfgs[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_cfg_m_ncfgs[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_cfg_m_ncfgs[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_cfg_m_ncfgs[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_cfg_m_ncfgs_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][23:16]);
          end
          if ((monitor_cfg_m_ncfgs_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][15:8]);
          end
          if ((monitor_cfg_m_ncfgs_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_cfg_m_ncfgs_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_cfg_m_ncfgs[monitor_cfg_m_ncfgs_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_write_nbytes_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_write_nbytes_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_write_nbytes_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_write_nbytes_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_write_nbytes, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_write_nbytes); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_write_nbytes_DEPTH - monitor_write_nbytes_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_nbytes[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_nbytes[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_write_nbytes[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_write_nbytes[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_nbytes[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_nbytes[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_write_nbytes_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][23:16]);
          end
          if ((monitor_write_nbytes_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][15:8]);
          end
          if ((monitor_write_nbytes_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_write_nbytes_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_nbytes[monitor_write_nbytes_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_write_npromoted_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_write_npromoted_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_write_npromoted_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_write_npromoted_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_write_npromoted, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_write_npromoted); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_write_npromoted_DEPTH - monitor_write_npromoted_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_npromoted[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_npromoted[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_write_npromoted[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_write_npromoted[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_npromoted[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_npromoted[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_write_npromoted_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][23:16]);
          end
          if ((monitor_write_npromoted_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][15:8]);
          end
          if ((monitor_write_npromoted_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_write_npromoted_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npromoted[monitor_write_npromoted_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_write_ndropped_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_write_ndropped_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_write_ndropped_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_write_ndropped_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_write_ndropped, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_write_ndropped); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_write_ndropped_DEPTH - monitor_write_ndropped_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_ndropped[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_ndropped[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_write_ndropped[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_write_ndropped[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_ndropped[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_ndropped[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_write_ndropped_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][23:16]);
          end
          if ((monitor_write_ndropped_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][15:8]);
          end
          if ((monitor_write_ndropped_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_write_ndropped_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_ndropped[monitor_write_ndropped_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_monitor_write_npackets_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [monitor_write_npackets_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (monitor_write_npackets_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (monitor_write_npackets_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_monitor_write_npackets, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_monitor_write_npackets); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (monitor_write_npackets_DEPTH - monitor_write_npackets_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_npackets[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_npackets[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_monitor_write_npackets[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_monitor_write_npackets[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_monitor_write_npackets[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_monitor_write_npackets[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[i]);
          end
      end 
      if (factor == 4) begin
          if ((monitor_write_npackets_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][23:16]);
          end
          if ((monitor_write_npackets_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][15:8]);
          end
          if ((monitor_write_npackets_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((monitor_write_npackets_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_monitor_write_npackets[monitor_write_npackets_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_BUS_A_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
endmodule
