// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

`define TV_OUT_mAxis_TDATA "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat"
`define EGRESS_STATUS_mAxis_TDATA "./stream_egress_status_mAxis_V_data_V.dat"
`define TV_OUT_mAxis_TKEEP "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat"
`define EGRESS_STATUS_mAxis_TKEEP "./stream_egress_status_mAxis_V_keep_V.dat"
`define TV_OUT_mAxis_TSTRB "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat"
`define EGRESS_STATUS_mAxis_TSTRB "./stream_egress_status_mAxis_V_strb_V.dat"
`define TV_OUT_mAxis_TUSER "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat"
`define EGRESS_STATUS_mAxis_TUSER "./stream_egress_status_mAxis_V_user_V.dat"
`define TV_OUT_mAxis_TLAST "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat"
`define EGRESS_STATUS_mAxis_TLAST "./stream_egress_status_mAxis_V_last_V.dat"
`define TV_OUT_mAxis_TID "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat"
`define EGRESS_STATUS_mAxis_TID "./stream_egress_status_mAxis_V_id_V.dat"
`define TV_OUT_mAxis_TDEST "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat"
`define EGRESS_STATUS_mAxis_TDEST "./stream_egress_status_mAxis_V_dest_V.dat"

`define AUTOTB_TRANSACTION_NUM 1

module AESL_axi_s_mAxis (
    input clk,
    input reset,
    input [64 - 1:0] TRAN_mAxis_TDATA,
    input [8 - 1:0] TRAN_mAxis_TKEEP,
    input [8 - 1:0] TRAN_mAxis_TSTRB,
    input [4 - 1:0] TRAN_mAxis_TUSER,
    input TRAN_mAxis_TLAST,
    input TRAN_mAxis_TID,
    input TRAN_mAxis_TDEST,
    input TRAN_mAxis_TVALID,
    output TRAN_mAxis_TREADY,
    input ready,
    input done,
    output [31:0] transaction);

    wire TRAN_mAxis_TVALID_temp;
    wire mAxis_TDATA_full;
    wire mAxis_TDATA_empty;
    reg mAxis_TDATA_write_en;
    reg [64 - 1:0] mAxis_TDATA_write_data;
    reg mAxis_TDATA_read_en;
    wire [64 - 1:0] mAxis_TDATA_read_data;
    
    fifo #(10921, 64) fifo_mAxis_TDATA (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TDATA_write_en),
        .write_data(mAxis_TDATA_write_data),
        .read_clock(clk),
        .read_en(mAxis_TDATA_read_en),
        .read_data(mAxis_TDATA_read_data),
        .full(mAxis_TDATA_full),
        .empty(mAxis_TDATA_empty));
    
    always @ (*) begin
        mAxis_TDATA_write_en <= TRAN_mAxis_TVALID;
        mAxis_TDATA_write_data <= TRAN_mAxis_TDATA;
        mAxis_TDATA_read_en <= 0;
    end
    wire mAxis_TKEEP_full;
    wire mAxis_TKEEP_empty;
    reg mAxis_TKEEP_write_en;
    reg [8 - 1:0] mAxis_TKEEP_write_data;
    reg mAxis_TKEEP_read_en;
    wire [8 - 1:0] mAxis_TKEEP_read_data;
    
    fifo #(10921, 8) fifo_mAxis_TKEEP (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TKEEP_write_en),
        .write_data(mAxis_TKEEP_write_data),
        .read_clock(clk),
        .read_en(mAxis_TKEEP_read_en),
        .read_data(mAxis_TKEEP_read_data),
        .full(mAxis_TKEEP_full),
        .empty(mAxis_TKEEP_empty));
    
    always @ (*) begin
        mAxis_TKEEP_write_en <= TRAN_mAxis_TVALID;
        mAxis_TKEEP_write_data <= TRAN_mAxis_TKEEP;
        mAxis_TKEEP_read_en <= 0;
    end
    wire mAxis_TSTRB_full;
    wire mAxis_TSTRB_empty;
    reg mAxis_TSTRB_write_en;
    reg [8 - 1:0] mAxis_TSTRB_write_data;
    reg mAxis_TSTRB_read_en;
    wire [8 - 1:0] mAxis_TSTRB_read_data;
    
    fifo #(10921, 8) fifo_mAxis_TSTRB (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TSTRB_write_en),
        .write_data(mAxis_TSTRB_write_data),
        .read_clock(clk),
        .read_en(mAxis_TSTRB_read_en),
        .read_data(mAxis_TSTRB_read_data),
        .full(mAxis_TSTRB_full),
        .empty(mAxis_TSTRB_empty));
    
    always @ (*) begin
        mAxis_TSTRB_write_en <= TRAN_mAxis_TVALID;
        mAxis_TSTRB_write_data <= TRAN_mAxis_TSTRB;
        mAxis_TSTRB_read_en <= 0;
    end
    wire mAxis_TUSER_full;
    wire mAxis_TUSER_empty;
    reg mAxis_TUSER_write_en;
    reg [4 - 1:0] mAxis_TUSER_write_data;
    reg mAxis_TUSER_read_en;
    wire [4 - 1:0] mAxis_TUSER_read_data;
    
    fifo #(10921, 4) fifo_mAxis_TUSER (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TUSER_write_en),
        .write_data(mAxis_TUSER_write_data),
        .read_clock(clk),
        .read_en(mAxis_TUSER_read_en),
        .read_data(mAxis_TUSER_read_data),
        .full(mAxis_TUSER_full),
        .empty(mAxis_TUSER_empty));
    
    always @ (*) begin
        mAxis_TUSER_write_en <= TRAN_mAxis_TVALID;
        mAxis_TUSER_write_data <= TRAN_mAxis_TUSER;
        mAxis_TUSER_read_en <= 0;
    end
    wire mAxis_TLAST_full;
    wire mAxis_TLAST_empty;
    reg mAxis_TLAST_write_en;
    reg [1 - 1:0] mAxis_TLAST_write_data;
    reg mAxis_TLAST_read_en;
    wire [1 - 1:0] mAxis_TLAST_read_data;
    
    fifo #(10921, 1) fifo_mAxis_TLAST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TLAST_write_en),
        .write_data(mAxis_TLAST_write_data),
        .read_clock(clk),
        .read_en(mAxis_TLAST_read_en),
        .read_data(mAxis_TLAST_read_data),
        .full(mAxis_TLAST_full),
        .empty(mAxis_TLAST_empty));
    
    always @ (*) begin
        mAxis_TLAST_write_en <= TRAN_mAxis_TVALID;
        mAxis_TLAST_write_data <= TRAN_mAxis_TLAST;
        mAxis_TLAST_read_en <= 0;
    end
    wire mAxis_TID_full;
    wire mAxis_TID_empty;
    reg mAxis_TID_write_en;
    reg [1 - 1:0] mAxis_TID_write_data;
    reg mAxis_TID_read_en;
    wire [1 - 1:0] mAxis_TID_read_data;
    
    fifo #(10921, 1) fifo_mAxis_TID (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TID_write_en),
        .write_data(mAxis_TID_write_data),
        .read_clock(clk),
        .read_en(mAxis_TID_read_en),
        .read_data(mAxis_TID_read_data),
        .full(mAxis_TID_full),
        .empty(mAxis_TID_empty));
    
    always @ (*) begin
        mAxis_TID_write_en <= TRAN_mAxis_TVALID;
        mAxis_TID_write_data <= TRAN_mAxis_TID;
        mAxis_TID_read_en <= 0;
    end
    wire mAxis_TDEST_full;
    wire mAxis_TDEST_empty;
    reg mAxis_TDEST_write_en;
    reg [1 - 1:0] mAxis_TDEST_write_data;
    reg mAxis_TDEST_read_en;
    wire [1 - 1:0] mAxis_TDEST_read_data;
    
    fifo #(10921, 1) fifo_mAxis_TDEST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(mAxis_TDEST_write_en),
        .write_data(mAxis_TDEST_write_data),
        .read_clock(clk),
        .read_en(mAxis_TDEST_read_en),
        .read_data(mAxis_TDEST_read_data),
        .full(mAxis_TDEST_full),
        .empty(mAxis_TDEST_empty));
    
    always @ (*) begin
        mAxis_TDEST_write_en <= TRAN_mAxis_TVALID;
        mAxis_TDEST_write_data <= TRAN_mAxis_TDEST;
        mAxis_TDEST_read_en <= 0;
    end
    assign TRAN_mAxis_TVALID = TRAN_mAxis_TVALID_temp;

    
    assign TRAN_mAxis_TREADY = ~(mAxis_TDATA_full || mAxis_TKEEP_full || mAxis_TSTRB_full || mAxis_TUSER_full || mAxis_TLAST_full || mAxis_TID_full || mAxis_TDEST_full);
    
    function is_blank_char(input [7:0] in_char);
        if (in_char == " " || in_char == "\011" || in_char == "\012" || in_char == "\015") begin
            is_blank_char = 1;
        end else begin
            is_blank_char = 0;
        end
    endfunction
    
    function [175:0] read_token(input integer fp);
        integer ret;
        begin
            read_token = "";
                    ret = 0;
                    ret = $fscanf(fp,"%s",read_token);
        end
    endfunction
    
    function [175:0] rm_0x(input [175:0] token);
        reg [175:0] token_tmp;
        integer i;
        begin
            token_tmp = "";
            for (i = 0; token[15:0] != "0x"; token = token >> 8) begin
                token_tmp = (token[7:0] << (8 * i)) | token_tmp;
                i = i + 1;
            end
            rm_0x = token_tmp;
        end
    endfunction
    
    reg done_1;
    
    always @ (posedge clk or reset) begin
        if (~reset) begin
            done_1 <= 0;
        end else begin
            done_1 <= done;
        end
    end
    
    reg [31:0] transaction_save_mAxis_TDATA;
    
    assign transaction = transaction_save_mAxis_TDATA;
    
    initial begin : AXI_stream_receiver_mAxis_TDATA
        integer fp;
        reg [64 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TDATA = 0;
        fifo_mAxis_TDATA.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TDATA, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TDATA);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TDATA);
                while (~fifo_mAxis_TDATA.empty) begin
                    fifo_mAxis_TDATA.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TDATA = transaction_save_mAxis_TDATA + 1;
                fifo_mAxis_TDATA.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_mAxis_TKEEP;
    
    initial begin : AXI_stream_receiver_mAxis_TKEEP
        integer fp;
        reg [8 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TKEEP = 0;
        fifo_mAxis_TKEEP.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TKEEP, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TKEEP);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TKEEP);
                while (~fifo_mAxis_TKEEP.empty) begin
                    fifo_mAxis_TKEEP.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TKEEP = transaction_save_mAxis_TKEEP + 1;
                fifo_mAxis_TKEEP.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_mAxis_TSTRB;
    
    initial begin : AXI_stream_receiver_mAxis_TSTRB
        integer fp;
        reg [8 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TSTRB = 0;
        fifo_mAxis_TSTRB.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TSTRB, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TSTRB);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TSTRB);
                while (~fifo_mAxis_TSTRB.empty) begin
                    fifo_mAxis_TSTRB.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TSTRB = transaction_save_mAxis_TSTRB + 1;
                fifo_mAxis_TSTRB.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_mAxis_TUSER;
    
    initial begin : AXI_stream_receiver_mAxis_TUSER
        integer fp;
        reg [4 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TUSER = 0;
        fifo_mAxis_TUSER.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TUSER, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TUSER);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TUSER);
                while (~fifo_mAxis_TUSER.empty) begin
                    fifo_mAxis_TUSER.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TUSER = transaction_save_mAxis_TUSER + 1;
                fifo_mAxis_TUSER.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_mAxis_TLAST;
    
    initial begin : AXI_stream_receiver_mAxis_TLAST
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TLAST = 0;
        fifo_mAxis_TLAST.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TLAST, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TLAST);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TLAST);
                while (~fifo_mAxis_TLAST.empty) begin
                    fifo_mAxis_TLAST.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TLAST = transaction_save_mAxis_TLAST + 1;
                fifo_mAxis_TLAST.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_mAxis_TID;
    
    initial begin : AXI_stream_receiver_mAxis_TID
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TID = 0;
        fifo_mAxis_TID.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TID, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TID);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TID);
                while (~fifo_mAxis_TID.empty) begin
                    fifo_mAxis_TID.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TID = transaction_save_mAxis_TID + 1;
                fifo_mAxis_TID.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_mAxis_TDEST;
    
    initial begin : AXI_stream_receiver_mAxis_TDEST
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_mAxis_TDEST = 0;
        fifo_mAxis_TDEST.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_mAxis_TDEST, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_mAxis_TDEST);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_mAxis_TDEST);
                while (~fifo_mAxis_TDEST.empty) begin
                    fifo_mAxis_TDEST.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_mAxis_TDEST = transaction_save_mAxis_TDEST + 1;
                fifo_mAxis_TDEST.clear();
                $fclose(fp);
            end
        end
    end

endmodule
