// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

`define TV_IN_sAxis_TDATA "./c.DuneDataCompressionCore.autotvin_sAxis_V_data_V.dat"
`define INGRESS_STATUS_sAxis_TDATA "./stream_ingress_status_sAxis_V_data_V.dat"
`define TV_IN_sAxis_TKEEP "./c.DuneDataCompressionCore.autotvin_sAxis_V_keep_V.dat"
`define INGRESS_STATUS_sAxis_TKEEP "./stream_ingress_status_sAxis_V_keep_V.dat"
`define TV_IN_sAxis_TSTRB "./c.DuneDataCompressionCore.autotvin_sAxis_V_strb_V.dat"
`define INGRESS_STATUS_sAxis_TSTRB "./stream_ingress_status_sAxis_V_strb_V.dat"
`define TV_IN_sAxis_TUSER "./c.DuneDataCompressionCore.autotvin_sAxis_V_user_V.dat"
`define INGRESS_STATUS_sAxis_TUSER "./stream_ingress_status_sAxis_V_user_V.dat"
`define TV_IN_sAxis_TLAST "./c.DuneDataCompressionCore.autotvin_sAxis_V_last_V.dat"
`define INGRESS_STATUS_sAxis_TLAST "./stream_ingress_status_sAxis_V_last_V.dat"
`define TV_IN_sAxis_TID "./c.DuneDataCompressionCore.autotvin_sAxis_V_id_V.dat"
`define INGRESS_STATUS_sAxis_TID "./stream_ingress_status_sAxis_V_id_V.dat"
`define TV_IN_sAxis_TDEST "./c.DuneDataCompressionCore.autotvin_sAxis_V_dest_V.dat"
`define INGRESS_STATUS_sAxis_TDEST "./stream_ingress_status_sAxis_V_dest_V.dat"

`define AUTOTB_TRANSACTION_NUM 1

module AESL_axi_s_sAxis (
    input clk,
    input reset,
    output [64 - 1:0] TRAN_sAxis_TDATA,
    output [8 - 1:0] TRAN_sAxis_TKEEP,
    output [8 - 1:0] TRAN_sAxis_TSTRB,
    output [4 - 1:0] TRAN_sAxis_TUSER,
    output TRAN_sAxis_TLAST,
    output TRAN_sAxis_TID,
    output TRAN_sAxis_TDEST,
    output TRAN_sAxis_TVALID,
    input TRAN_sAxis_TREADY,
    input ready,
    input done,
    output [31:0] transaction);

    wire TRAN_sAxis_TVALID_temp;
    wire sAxis_TDATA_full;
    wire sAxis_TDATA_empty;
    reg sAxis_TDATA_write_en;
    reg [64 - 1:0] sAxis_TDATA_write_data;
    reg sAxis_TDATA_read_en;
    wire [64 - 1:0] sAxis_TDATA_read_data;
    
    fifo #(30720, 64) fifo_sAxis_TDATA (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TDATA_write_en),
        .write_data(sAxis_TDATA_write_data),
        .read_clock(clk),
        .read_en(sAxis_TDATA_read_en),
        .read_data(sAxis_TDATA_read_data),
        .full(sAxis_TDATA_full),
        .empty(sAxis_TDATA_empty));
    
    always @ (*) begin
        sAxis_TDATA_write_en <= 0;
        sAxis_TDATA_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TDATA = sAxis_TDATA_read_data;
    wire sAxis_TKEEP_full;
    wire sAxis_TKEEP_empty;
    reg sAxis_TKEEP_write_en;
    reg [8 - 1:0] sAxis_TKEEP_write_data;
    reg sAxis_TKEEP_read_en;
    wire [8 - 1:0] sAxis_TKEEP_read_data;
    
    fifo #(30720, 8) fifo_sAxis_TKEEP (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TKEEP_write_en),
        .write_data(sAxis_TKEEP_write_data),
        .read_clock(clk),
        .read_en(sAxis_TKEEP_read_en),
        .read_data(sAxis_TKEEP_read_data),
        .full(sAxis_TKEEP_full),
        .empty(sAxis_TKEEP_empty));
    
    always @ (*) begin
        sAxis_TKEEP_write_en <= 0;
        sAxis_TKEEP_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TKEEP = sAxis_TKEEP_read_data;
    wire sAxis_TSTRB_full;
    wire sAxis_TSTRB_empty;
    reg sAxis_TSTRB_write_en;
    reg [8 - 1:0] sAxis_TSTRB_write_data;
    reg sAxis_TSTRB_read_en;
    wire [8 - 1:0] sAxis_TSTRB_read_data;
    
    fifo #(30720, 8) fifo_sAxis_TSTRB (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TSTRB_write_en),
        .write_data(sAxis_TSTRB_write_data),
        .read_clock(clk),
        .read_en(sAxis_TSTRB_read_en),
        .read_data(sAxis_TSTRB_read_data),
        .full(sAxis_TSTRB_full),
        .empty(sAxis_TSTRB_empty));
    
    always @ (*) begin
        sAxis_TSTRB_write_en <= 0;
        sAxis_TSTRB_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TSTRB = sAxis_TSTRB_read_data;
    wire sAxis_TUSER_full;
    wire sAxis_TUSER_empty;
    reg sAxis_TUSER_write_en;
    reg [4 - 1:0] sAxis_TUSER_write_data;
    reg sAxis_TUSER_read_en;
    wire [4 - 1:0] sAxis_TUSER_read_data;
    
    fifo #(30720, 4) fifo_sAxis_TUSER (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TUSER_write_en),
        .write_data(sAxis_TUSER_write_data),
        .read_clock(clk),
        .read_en(sAxis_TUSER_read_en),
        .read_data(sAxis_TUSER_read_data),
        .full(sAxis_TUSER_full),
        .empty(sAxis_TUSER_empty));
    
    always @ (*) begin
        sAxis_TUSER_write_en <= 0;
        sAxis_TUSER_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TUSER = sAxis_TUSER_read_data;
    wire sAxis_TLAST_full;
    wire sAxis_TLAST_empty;
    reg sAxis_TLAST_write_en;
    reg [1 - 1:0] sAxis_TLAST_write_data;
    reg sAxis_TLAST_read_en;
    wire [1 - 1:0] sAxis_TLAST_read_data;
    
    fifo #(30720, 1) fifo_sAxis_TLAST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TLAST_write_en),
        .write_data(sAxis_TLAST_write_data),
        .read_clock(clk),
        .read_en(sAxis_TLAST_read_en),
        .read_data(sAxis_TLAST_read_data),
        .full(sAxis_TLAST_full),
        .empty(sAxis_TLAST_empty));
    
    always @ (*) begin
        sAxis_TLAST_write_en <= 0;
        sAxis_TLAST_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TLAST = sAxis_TLAST_read_data;
    wire sAxis_TID_full;
    wire sAxis_TID_empty;
    reg sAxis_TID_write_en;
    reg [1 - 1:0] sAxis_TID_write_data;
    reg sAxis_TID_read_en;
    wire [1 - 1:0] sAxis_TID_read_data;
    
    fifo #(30720, 1) fifo_sAxis_TID (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TID_write_en),
        .write_data(sAxis_TID_write_data),
        .read_clock(clk),
        .read_en(sAxis_TID_read_en),
        .read_data(sAxis_TID_read_data),
        .full(sAxis_TID_full),
        .empty(sAxis_TID_empty));
    
    always @ (*) begin
        sAxis_TID_write_en <= 0;
        sAxis_TID_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TID = sAxis_TID_read_data;
    wire sAxis_TDEST_full;
    wire sAxis_TDEST_empty;
    reg sAxis_TDEST_write_en;
    reg [1 - 1:0] sAxis_TDEST_write_data;
    reg sAxis_TDEST_read_en;
    wire [1 - 1:0] sAxis_TDEST_read_data;
    
    fifo #(30720, 1) fifo_sAxis_TDEST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(sAxis_TDEST_write_en),
        .write_data(sAxis_TDEST_write_data),
        .read_clock(clk),
        .read_en(sAxis_TDEST_read_en),
        .read_data(sAxis_TDEST_read_data),
        .full(sAxis_TDEST_full),
        .empty(sAxis_TDEST_empty));
    
    always @ (*) begin
        sAxis_TDEST_write_en <= 0;
        sAxis_TDEST_read_en <= TRAN_sAxis_TREADY & TRAN_sAxis_TVALID;
    end
    
    assign TRAN_sAxis_TDEST = sAxis_TDEST_read_data;
    assign TRAN_sAxis_TVALID = TRAN_sAxis_TVALID_temp;

    
    reg sAxis_TDATA_valid = 0; // ingress buffer indicator: sAxis_TDATA
    reg sAxis_TKEEP_valid = 0; // ingress buffer indicator: sAxis_TKEEP
    reg sAxis_TSTRB_valid = 0; // ingress buffer indicator: sAxis_TSTRB
    reg sAxis_TUSER_valid = 0; // ingress buffer indicator: sAxis_TUSER
    reg sAxis_TLAST_valid = 0; // ingress buffer indicator: sAxis_TLAST
    reg sAxis_TID_valid = 0; // ingress buffer indicator: sAxis_TID
    reg sAxis_TDEST_valid = 0; // ingress buffer indicator: sAxis_TDEST
    
    assign TRAN_sAxis_TVALID_temp = ~(sAxis_TDATA_empty || sAxis_TKEEP_empty || sAxis_TSTRB_empty || sAxis_TUSER_empty || sAxis_TLAST_empty || sAxis_TID_empty || sAxis_TDEST_empty) || (sAxis_TDATA_valid && sAxis_TKEEP_valid && sAxis_TSTRB_valid && sAxis_TUSER_valid && sAxis_TLAST_valid && sAxis_TID_valid && sAxis_TDEST_valid);
    
    function is_blank_char(input [7:0] in_char);
        if (in_char == " " || in_char == "\011" || in_char == "\012" || in_char == "\015") begin
            is_blank_char = 1;
        end else begin
            is_blank_char = 0;
        end
    endfunction
    
    function [175:0] read_token(input integer fp);
        integer ret;
        begin
            read_token = "";
                    ret = 0;
                    ret = $fscanf(fp,"%s",read_token);
        end
    endfunction
    
    function [175:0] rm_0x(input [175:0] token);
        reg [175:0] token_tmp;
        integer i;
        begin
            token_tmp = "";
            for (i = 0; token[15:0] != "0x"; token = token >> 8) begin
                token_tmp = (token[7:0] << (8 * i)) | token_tmp;
                i = i + 1;
            end
            rm_0x = token_tmp;
        end
    endfunction
    
    reg [31:0] transaction_load_sAxis_TDATA;
    
    assign transaction = transaction_load_sAxis_TDATA;
    
    initial begin : AXI_stream_driver_sAxis_TDATA
        integer fp;
        reg [175:0] token;
        reg [64 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TDATA = 0;
        fifo_sAxis_TDATA.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TDATA, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TDATA);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TDATA, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TDATA);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TDATA.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TDATA.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TDATA.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TDATA_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TDATA.snapshot();
                end else begin
                    fifo_sAxis_TDATA.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TDATA = transaction_load_sAxis_TDATA + 1;
            end
        end
    end
    
    reg [31:0] transaction_load_sAxis_TKEEP;
    
    initial begin : AXI_stream_driver_sAxis_TKEEP
        integer fp;
        reg [175:0] token;
        reg [8 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TKEEP = 0;
        fifo_sAxis_TKEEP.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TKEEP, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TKEEP);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TKEEP, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TKEEP);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TKEEP.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TKEEP.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TKEEP.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TKEEP_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TKEEP.snapshot();
                end else begin
                    fifo_sAxis_TKEEP.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TKEEP = transaction_load_sAxis_TKEEP + 1;
            end
        end
    end
    
    reg [31:0] transaction_load_sAxis_TSTRB;
    
    initial begin : AXI_stream_driver_sAxis_TSTRB
        integer fp;
        reg [175:0] token;
        reg [8 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TSTRB = 0;
        fifo_sAxis_TSTRB.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TSTRB, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TSTRB);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TSTRB, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TSTRB);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TSTRB.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TSTRB.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TSTRB.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TSTRB_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TSTRB.snapshot();
                end else begin
                    fifo_sAxis_TSTRB.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TSTRB = transaction_load_sAxis_TSTRB + 1;
            end
        end
    end
    
    reg [31:0] transaction_load_sAxis_TUSER;
    
    initial begin : AXI_stream_driver_sAxis_TUSER
        integer fp;
        reg [175:0] token;
        reg [4 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TUSER = 0;
        fifo_sAxis_TUSER.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TUSER, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TUSER);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TUSER, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TUSER);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TUSER.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TUSER.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TUSER.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TUSER_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TUSER.snapshot();
                end else begin
                    fifo_sAxis_TUSER.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TUSER = transaction_load_sAxis_TUSER + 1;
            end
        end
    end
    
    reg [31:0] transaction_load_sAxis_TLAST;
    
    initial begin : AXI_stream_driver_sAxis_TLAST
        integer fp;
        reg [175:0] token;
        reg [1 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TLAST = 0;
        fifo_sAxis_TLAST.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TLAST, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TLAST);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TLAST, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TLAST);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TLAST.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TLAST.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TLAST.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TLAST_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TLAST.snapshot();
                end else begin
                    fifo_sAxis_TLAST.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TLAST = transaction_load_sAxis_TLAST + 1;
            end
        end
    end
    
    reg [31:0] transaction_load_sAxis_TID;
    
    initial begin : AXI_stream_driver_sAxis_TID
        integer fp;
        reg [175:0] token;
        reg [1 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TID = 0;
        fifo_sAxis_TID.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TID, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TID);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TID, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TID);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TID.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TID.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TID.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TID_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TID.snapshot();
                end else begin
                    fifo_sAxis_TID.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TID = transaction_load_sAxis_TID + 1;
            end
        end
    end
    
    reg [31:0] transaction_load_sAxis_TDEST;
    
    initial begin : AXI_stream_driver_sAxis_TDEST
        integer fp;
        reg [175:0] token;
        reg [1 - 1:0] data;
        reg [175:0] data_integer;
        integer fp_ingress_status;
        reg [175:0] token_ingress_status;
        reg [31:0] ingress_status;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_sAxis_TDEST = 0;
        fifo_sAxis_TDEST.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_sAxis_TDEST, "r");
        if (fp == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_sAxis_TDEST);
            $finish;
        end
        fp_ingress_status = $fopen(`INGRESS_STATUS_sAxis_TDEST, "r");
        if (fp_ingress_status == 0) begin // Failed to open file
            $display("ERROR: Failed to open file \"%s\"!", `INGRESS_STATUS_sAxis_TDEST);
            $finish;
        end
        token = read_token(fp);
        token_ingress_status = read_token(fp_ingress_status);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        token_ingress_status = read_token(fp_ingress_status);
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // skip transaction number
                    token_ingress_status = read_token(fp_ingress_status); // load ingress status at beginning of transaction
                    fifo_sAxis_TDEST.clear();
                    token = read_token(fp);
                    ret = $sscanf(token_ingress_status, "%d", ingress_status);
                    token_ingress_status = read_token(fp_ingress_status);
                    while (token != "[[/transaction]]") begin
                        if (fifo_sAxis_TDEST.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_sAxis_TDEST.push(data);
                        token = read_token(fp);
                        ret = $sscanf(token_ingress_status, "%d", ingress_status);
                        token_ingress_status = read_token(fp_ingress_status);
                    end
                    sAxis_TDEST_valid = (ingress_status > 0);
                    token = read_token(fp);
                    token_ingress_status = read_token(fp_ingress_status);
                    fifo_sAxis_TDEST.snapshot();
                end else begin
                    fifo_sAxis_TDEST.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                    if (fp_ingress_status != 0) begin
                        $fclose(fp_ingress_status);
                        fp_ingress_status = 0;
                    end
                end
                transaction_load_sAxis_TDEST = transaction_load_sAxis_TDEST + 1;
            end
        end
    end

endmodule
