// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      DuneDataCompressionCore
`define AUTOTB_DUT_INST AESL_inst_DuneDataCompressionCore
`define AUTOTB_TOP      apatb_DuneDataCompressionCore_top
`define AUTOTB_LAT_RESULT_FILE "DuneDataCompressionCore.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "DuneDataCompressionCore.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_DuneDataCompressionCore_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_CLOCK_PERIOD_DIV2 4.00

`define AESL_DEPTH_sAxis_V_data_V 1
`define AESL_DEPTH_sAxis_V_keep_V 1
`define AESL_DEPTH_sAxis_V_strb_V 1
`define AESL_DEPTH_sAxis_V_user_V 1
`define AESL_DEPTH_sAxis_V_last_V 1
`define AESL_DEPTH_sAxis_V_id_V 1
`define AESL_DEPTH_sAxis_V_dest_V 1
`define AESL_DEPTH_mAxis_V_data_V 1
`define AESL_DEPTH_mAxis_V_keep_V 1
`define AESL_DEPTH_mAxis_V_strb_V 1
`define AESL_DEPTH_mAxis_V_user_V 1
`define AESL_DEPTH_mAxis_V_last_V 1
`define AESL_DEPTH_mAxis_V_id_V 1
`define AESL_DEPTH_mAxis_V_dest_V 1
`define AESL_DEPTH_moduleIdx_V 1
`define AESL_DEPTH_config_init 1
`define AESL_DEPTH_config_mode 1
`define AESL_DEPTH_config_limit 1
`define AESL_DEPTH_config_chns_disabled 1
`define AESL_DEPTH_monitor_common_pattern 1
`define AESL_DEPTH_monitor_cfg_m_mode 1
`define AESL_DEPTH_monitor_cfg_m_ncfgs 1
`define AESL_DEPTH_monitor_read_summary_mask_V 1
`define AESL_DEPTH_monitor_read_summary_nframes 1
`define AESL_DEPTH_monitor_read_summary_nStates 1
`define AESL_DEPTH_monitor_read_errs_nFrameErrs 1
`define AESL_DEPTH_monitor_read_errs_nWibErrs 1
`define AESL_DEPTH_monitor_write_nbytes 1
`define AESL_DEPTH_monitor_write_npromoted 1
`define AESL_DEPTH_monitor_write_ndropped 1
`define AESL_DEPTH_monitor_write_npackets 1
`define AUTOTB_TVIN_sAxis_V_data_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_data_V.dat"
`define AUTOTB_TVIN_sAxis_V_keep_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_keep_V.dat"
`define AUTOTB_TVIN_sAxis_V_strb_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_strb_V.dat"
`define AUTOTB_TVIN_sAxis_V_user_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_user_V.dat"
`define AUTOTB_TVIN_sAxis_V_last_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_last_V.dat"
`define AUTOTB_TVIN_sAxis_V_id_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_id_V.dat"
`define AUTOTB_TVIN_sAxis_V_dest_V  "./c.DuneDataCompressionCore.autotvin_sAxis_V_dest_V.dat"
`define AUTOTB_TVIN_mAxis_V_data_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_data_V.dat"
`define AUTOTB_TVIN_mAxis_V_keep_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_keep_V.dat"
`define AUTOTB_TVIN_mAxis_V_strb_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_strb_V.dat"
`define AUTOTB_TVIN_mAxis_V_user_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_user_V.dat"
`define AUTOTB_TVIN_mAxis_V_last_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_last_V.dat"
`define AUTOTB_TVIN_mAxis_V_id_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_id_V.dat"
`define AUTOTB_TVIN_mAxis_V_dest_V  "./c.DuneDataCompressionCore.autotvin_mAxis_V_dest_V.dat"
`define AUTOTB_TVIN_config_init  "./c.DuneDataCompressionCore.autotvin_config_init.dat"
`define AUTOTB_TVIN_config_mode  "./c.DuneDataCompressionCore.autotvin_config_mode.dat"
`define AUTOTB_TVIN_config_limit  "./c.DuneDataCompressionCore.autotvin_config_limit.dat"
`define AUTOTB_TVIN_sAxis_V_data_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_data_V.dat"
`define AUTOTB_TVIN_sAxis_V_keep_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_keep_V.dat"
`define AUTOTB_TVIN_sAxis_V_strb_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_strb_V.dat"
`define AUTOTB_TVIN_sAxis_V_user_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_user_V.dat"
`define AUTOTB_TVIN_sAxis_V_last_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_last_V.dat"
`define AUTOTB_TVIN_sAxis_V_id_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_id_V.dat"
`define AUTOTB_TVIN_sAxis_V_dest_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_sAxis_V_dest_V.dat"
`define AUTOTB_TVIN_mAxis_V_data_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_data_V.dat"
`define AUTOTB_TVIN_mAxis_V_keep_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_keep_V.dat"
`define AUTOTB_TVIN_mAxis_V_strb_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_strb_V.dat"
`define AUTOTB_TVIN_mAxis_V_user_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_user_V.dat"
`define AUTOTB_TVIN_mAxis_V_last_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_last_V.dat"
`define AUTOTB_TVIN_mAxis_V_id_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_id_V.dat"
`define AUTOTB_TVIN_mAxis_V_dest_V_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_mAxis_V_dest_V.dat"
`define AUTOTB_TVIN_config_init_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_config_init.dat"
`define AUTOTB_TVIN_config_mode_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_config_mode.dat"
`define AUTOTB_TVIN_config_limit_out_wrapc  "./rtl.DuneDataCompressionCore.autotvin_config_limit.dat"
`define AUTOTB_TVOUT_mAxis_V_data_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat"
`define AUTOTB_TVOUT_mAxis_V_keep_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat"
`define AUTOTB_TVOUT_mAxis_V_strb_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat"
`define AUTOTB_TVOUT_mAxis_V_user_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat"
`define AUTOTB_TVOUT_mAxis_V_last_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat"
`define AUTOTB_TVOUT_mAxis_V_id_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat"
`define AUTOTB_TVOUT_mAxis_V_dest_V  "./c.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat"
`define AUTOTB_TVOUT_monitor_common_pattern  "./c.DuneDataCompressionCore.autotvout_monitor_common_pattern.dat"
`define AUTOTB_TVOUT_monitor_cfg_m_mode  "./c.DuneDataCompressionCore.autotvout_monitor_cfg_m_mode.dat"
`define AUTOTB_TVOUT_monitor_cfg_m_ncfgs  "./c.DuneDataCompressionCore.autotvout_monitor_cfg_m_ncfgs.dat"
`define AUTOTB_TVOUT_monitor_write_nbytes  "./c.DuneDataCompressionCore.autotvout_monitor_write_nbytes.dat"
`define AUTOTB_TVOUT_monitor_write_npromoted  "./c.DuneDataCompressionCore.autotvout_monitor_write_npromoted.dat"
`define AUTOTB_TVOUT_monitor_write_ndropped  "./c.DuneDataCompressionCore.autotvout_monitor_write_ndropped.dat"
`define AUTOTB_TVOUT_monitor_write_npackets  "./c.DuneDataCompressionCore.autotvout_monitor_write_npackets.dat"
`define AUTOTB_TVOUT_mAxis_V_data_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat"
`define AUTOTB_TVOUT_mAxis_V_keep_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat"
`define AUTOTB_TVOUT_mAxis_V_strb_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat"
`define AUTOTB_TVOUT_mAxis_V_user_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat"
`define AUTOTB_TVOUT_mAxis_V_last_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat"
`define AUTOTB_TVOUT_mAxis_V_id_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat"
`define AUTOTB_TVOUT_mAxis_V_dest_V_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat"
`define AUTOTB_TVOUT_monitor_common_pattern_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_common_pattern.dat"
`define AUTOTB_TVOUT_monitor_cfg_m_mode_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_cfg_m_mode.dat"
`define AUTOTB_TVOUT_monitor_cfg_m_ncfgs_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_cfg_m_ncfgs.dat"
`define AUTOTB_TVOUT_monitor_write_nbytes_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_write_nbytes.dat"
`define AUTOTB_TVOUT_monitor_write_npromoted_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_write_npromoted.dat"
`define AUTOTB_TVOUT_monitor_write_ndropped_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_write_ndropped.dat"
`define AUTOTB_TVOUT_monitor_write_npackets_out_wrapc  "./impl_rtl.DuneDataCompressionCore.autotvout_monitor_write_npackets.dat"
module `AUTOTB_TOP;

parameter AUTOTB_TRANSACTION_NUM = 1;
parameter PROGRESS_TIMEOUT = 10000000;
parameter LATENCY_ESTIMATION = 127501;
parameter LENGTH_sAxis_V_data_V = 30720;
parameter LENGTH_sAxis_V_keep_V = 30720;
parameter LENGTH_sAxis_V_strb_V = 30720;
parameter LENGTH_sAxis_V_user_V = 30720;
parameter LENGTH_sAxis_V_last_V = 30720;
parameter LENGTH_sAxis_V_id_V = 30720;
parameter LENGTH_sAxis_V_dest_V = 30720;
parameter LENGTH_mAxis_V_data_V = 10921;
parameter LENGTH_mAxis_V_keep_V = 10921;
parameter LENGTH_mAxis_V_strb_V = 10921;
parameter LENGTH_mAxis_V_user_V = 10921;
parameter LENGTH_mAxis_V_last_V = 10921;
parameter LENGTH_mAxis_V_id_V = 10921;
parameter LENGTH_mAxis_V_dest_V = 10921;
parameter LENGTH_config_init = 1;
parameter LENGTH_config_mode = 1;
parameter LENGTH_config_limit = 1;
parameter LENGTH_monitor_common_pattern = 1;
parameter LENGTH_monitor_cfg_m_mode = 1;
parameter LENGTH_monitor_cfg_m_ncfgs = 1;
parameter LENGTH_monitor_write_nbytes = 1;
parameter LENGTH_monitor_write_npromoted = 1;
parameter LENGTH_monitor_write_ndropped = 1;
parameter LENGTH_monitor_write_npackets = 1;

task read_token;
    input integer fp;
    output reg [175 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end
endtask

task post_check;
    input integer fp1;
    input integer fp2;
    reg [175 : 0] token1;
    reg [175 : 0] token2;
    reg [175 : 0] golden;
    reg [175 : 0] result;
    integer ret;
    begin
        read_token(fp1, token1);
        read_token(fp2, token2);
        if (token1 != "[[[runtime]]]" || token2 != "[[[runtime]]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
            $finish;
        end
        read_token(fp1, token1);
        read_token(fp2, token2);
        while (token1 != "[[[/runtime]]]" && token2 != "[[[/runtime]]]") begin
            if (token1 != "[[transaction]]" || token2 != "[[transaction]]") begin
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
            end
            read_token(fp1, token1);  // skip transaction number
            read_token(fp2, token2);  // skip transaction number
              read_token(fp1, token1);
              read_token(fp2, token2);
            while(token1 != "[[/transaction]]" && token2 != "[[/transaction]]") begin
                rm_0x(token1);
                ret = $sscanf(token1, "%x", golden);
                  if (ret != 1) begin
                      $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                  end
                rm_0x(token2);
                ret = $sscanf(token2, "%x", result);
                  if (ret != 1) begin
                      $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                  end
                if(golden != result) begin
                      $display("%x (expected) vs. %x (actual) - mismatch", golden, result);
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                end
                  read_token(fp1, token1);
                  read_token(fp2, token2);
            end
              read_token(fp1, token1);
              read_token(fp2, token2);
        end
    end
endtask

task rm_0x;
    inout reg [175 : 0] token;
    reg [175 : 0] token_tmp;
    integer idx;
    reg done;
    begin
      token_tmp = "";
      idx = 0;
       while (token[15 : 0] != "0x") begin
          token_tmp = (token[7:0] << 8*idx) | token_tmp;
          idx = idx + 1;
          token = token >> 8;
       end
       token = "";
       token = token_tmp;
     end
endtask
reg AESL_clock;
reg rst;
reg start;
reg ce;
reg tb_continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
wire [9 : 0] BUS_A_AWADDR;
wire  BUS_A_AWVALID;
wire  BUS_A_AWREADY;
wire  BUS_A_WVALID;
wire  BUS_A_WREADY;
wire [31 : 0] BUS_A_WDATA;
wire [3 : 0] BUS_A_WSTRB;
wire [9 : 0] BUS_A_ARADDR;
wire  BUS_A_ARVALID;
wire  BUS_A_ARREADY;
wire  BUS_A_RVALID;
wire  BUS_A_RREADY;
wire [31 : 0] BUS_A_RDATA;
wire [1 : 0] BUS_A_RRESP;
wire  BUS_A_BVALID;
wire  BUS_A_BREADY;
wire [1 : 0] BUS_A_BRESP;
wire  BUS_A_INTERRUPT;
wire [63 : 0] sAxis_TDATA;
wire [7 : 0] sAxis_TKEEP;
wire [7 : 0] sAxis_TSTRB;
wire [3 : 0] sAxis_TUSER;
wire [0 : 0] sAxis_TLAST;
wire [0 : 0] sAxis_TID;
wire [0 : 0] sAxis_TDEST;
wire [63 : 0] mAxis_TDATA;
wire [7 : 0] mAxis_TKEEP;
wire [7 : 0] mAxis_TSTRB;
wire [3 : 0] mAxis_TUSER;
wire [0 : 0] mAxis_TLAST;
wire [0 : 0] mAxis_TID;
wire [0 : 0] mAxis_TDEST;
wire [0 : 0] moduleIdx_V;
wire  mAxis_TVALID;
wire  mAxis_TREADY;
wire  sAxis_TVALID;
wire  sAxis_TREADY;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;
wire BUS_A_read_data_finish;
wire BUS_A_write_data_finish;
wire AESL_slave_start;
wire AESL_slave_write_start_in;
wire AESL_slave_write_start_finish;
reg AESL_slave_ready;
wire AESL_slave_output_done;
reg ready_rise = 0;
reg start_rise = 0;
reg slave_start_status = 0;
reg slave_done_status = 0;

wire ap_clk;
wire ap_rst_n;
wire ap_rst_n_n;

`AUTOTB_DUT `AUTOTB_DUT_INST(
    .s_axi_BUS_A_AWADDR(BUS_A_AWADDR),
    .s_axi_BUS_A_AWVALID(BUS_A_AWVALID),
    .s_axi_BUS_A_AWREADY(BUS_A_AWREADY),
    .s_axi_BUS_A_WVALID(BUS_A_WVALID),
    .s_axi_BUS_A_WREADY(BUS_A_WREADY),
    .s_axi_BUS_A_WDATA(BUS_A_WDATA),
    .s_axi_BUS_A_WSTRB(BUS_A_WSTRB),
    .s_axi_BUS_A_ARADDR(BUS_A_ARADDR),
    .s_axi_BUS_A_ARVALID(BUS_A_ARVALID),
    .s_axi_BUS_A_ARREADY(BUS_A_ARREADY),
    .s_axi_BUS_A_RVALID(BUS_A_RVALID),
    .s_axi_BUS_A_RREADY(BUS_A_RREADY),
    .s_axi_BUS_A_RDATA(BUS_A_RDATA),
    .s_axi_BUS_A_RRESP(BUS_A_RRESP),
    .s_axi_BUS_A_BVALID(BUS_A_BVALID),
    .s_axi_BUS_A_BREADY(BUS_A_BREADY),
    .s_axi_BUS_A_BRESP(BUS_A_BRESP),
    .interrupt(BUS_A_INTERRUPT),
    .ap_clk(ap_clk),
    .ap_rst_n(ap_rst_n),
    .sAxis_TDATA(sAxis_TDATA),
    .sAxis_TKEEP(sAxis_TKEEP),
    .sAxis_TSTRB(sAxis_TSTRB),
    .sAxis_TUSER(sAxis_TUSER),
    .sAxis_TLAST(sAxis_TLAST),
    .sAxis_TID(sAxis_TID),
    .sAxis_TDEST(sAxis_TDEST),
    .mAxis_TDATA(mAxis_TDATA),
    .mAxis_TKEEP(mAxis_TKEEP),
    .mAxis_TSTRB(mAxis_TSTRB),
    .mAxis_TUSER(mAxis_TUSER),
    .mAxis_TLAST(mAxis_TLAST),
    .mAxis_TID(mAxis_TID),
    .mAxis_TDEST(mAxis_TDEST),
    .moduleIdx_V(moduleIdx_V),
    .mAxis_TVALID(mAxis_TVALID),
    .mAxis_TREADY(mAxis_TREADY),
    .sAxis_TVALID(sAxis_TVALID),
    .sAxis_TREADY(sAxis_TREADY));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst_n = AESL_reset;
assign ap_rst_n_n = ~AESL_reset;
assign AESL_reset = rst;
assign AESL_start = start;
assign AESL_ce = ce;
assign AESL_continue = tb_continue;
  assign AESL_slave_write_start_in = slave_start_status  & BUS_A_write_data_finish;
  assign AESL_slave_start = AESL_slave_write_start_finish;
  assign AESL_done = slave_done_status  & BUS_A_read_data_finish;

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
    begin
        slave_start_status <= 1;
    end
    else begin
        if (AESL_start == 1 ) begin
            start_rise = 1;
        end
        if (start_rise == 1 && AESL_done == 1 ) begin
            slave_start_status <= 1;
        end
        if (AESL_slave_write_start_in == 1) begin 
            slave_start_status <= 0;
            start_rise = 0;
        end
    end
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
    begin
        AESL_slave_ready <= 0;
        ready_rise = 0;
    end
    else begin
        if (AESL_ready == 1 ) begin
            ready_rise = 1;
        end
        if (ready_rise == 1 && AESL_done_delay == 1 ) begin
            AESL_slave_ready <= 1;
        end
        if (AESL_slave_ready == 1) begin 
            AESL_slave_ready <= 0;
            ready_rise = 0;
        end
    end
end

always @ (posedge AESL_clock)
begin
    if (AESL_done == 1) begin
        slave_done_status <= 0;
    end
    else if (AESL_slave_output_done == 1 ) begin
        slave_done_status <= 1;
    end
end














// The signal of port moduleIdx_V
reg [0: 0] AESL_REG_moduleIdx_V = 0;
assign moduleIdx_V = AESL_REG_moduleIdx_V;

















reg [31:0] ap_c_n_tvin_trans_num_sAxis_V_data_V;

reg sAxis_ready_reg; // for self-sync

wire sAxis_ready;
wire sAxis_done;
wire [31:0] sAxis_transaction;
wire axi_s_sAxis_TVALID;
wire axi_s_sAxis_TREADY;

AESL_axi_s_sAxis AESL_AXI_S_sAxis(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_sAxis_TDATA(sAxis_TDATA),
    .TRAN_sAxis_TKEEP(sAxis_TKEEP),
    .TRAN_sAxis_TSTRB(sAxis_TSTRB),
    .TRAN_sAxis_TUSER(sAxis_TUSER),
    .TRAN_sAxis_TLAST(sAxis_TLAST),
    .TRAN_sAxis_TID(sAxis_TID),
    .TRAN_sAxis_TDEST(sAxis_TDEST),
    .TRAN_sAxis_TVALID(axi_s_sAxis_TVALID),
    .TRAN_sAxis_TREADY(axi_s_sAxis_TREADY),
    .ready(sAxis_ready),
    .done(sAxis_done),
    .transaction(sAxis_transaction));

assign sAxis_ready = sAxis_ready_reg | ready_initial;
assign sAxis_done = 0;

assign sAxis_TVALID = axi_s_sAxis_TVALID;

assign axi_s_sAxis_TREADY = sAxis_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_mAxis_V_data_V;

reg mAxis_ready_reg; // for self-sync

wire mAxis_ready;
wire mAxis_done;
wire [31:0] mAxis_transaction;
wire axi_s_mAxis_TVALID;
wire axi_s_mAxis_TREADY;

AESL_axi_s_mAxis AESL_AXI_S_mAxis(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_mAxis_TDATA(mAxis_TDATA),
    .TRAN_mAxis_TKEEP(mAxis_TKEEP),
    .TRAN_mAxis_TSTRB(mAxis_TSTRB),
    .TRAN_mAxis_TUSER(mAxis_TUSER),
    .TRAN_mAxis_TLAST(mAxis_TLAST),
    .TRAN_mAxis_TID(mAxis_TID),
    .TRAN_mAxis_TDEST(mAxis_TDEST),
    .TRAN_mAxis_TVALID(axi_s_mAxis_TVALID),
    .TRAN_mAxis_TREADY(axi_s_mAxis_TREADY),
    .ready(mAxis_ready),
    .done(mAxis_done),
    .transaction(mAxis_transaction));

assign mAxis_ready = 0;
assign mAxis_done = AESL_done;

assign axi_s_mAxis_TVALID = mAxis_TVALID;

reg reg_mAxis_TREADY;
initial begin : gen_reg_mAxis_TREADY_process
    integer proc_rand;
    reg_mAxis_TREADY = axi_s_mAxis_TREADY;
    while(1)
    begin
        @(axi_s_mAxis_TREADY);
        reg_mAxis_TREADY = axi_s_mAxis_TREADY;
    end
end


assign mAxis_TREADY = reg_mAxis_TREADY;

AESL_axi_slave_BUS_A AESL_AXI_SLAVE_BUS_A(
    .clk   (AESL_clock),
    .reset (AESL_reset),
    .TRAN_s_axi_BUS_A_AWADDR (BUS_A_AWADDR),
    .TRAN_s_axi_BUS_A_AWVALID (BUS_A_AWVALID),
    .TRAN_s_axi_BUS_A_AWREADY (BUS_A_AWREADY),
    .TRAN_s_axi_BUS_A_WVALID (BUS_A_WVALID),
    .TRAN_s_axi_BUS_A_WREADY (BUS_A_WREADY),
    .TRAN_s_axi_BUS_A_WDATA (BUS_A_WDATA),
    .TRAN_s_axi_BUS_A_WSTRB (BUS_A_WSTRB),
    .TRAN_s_axi_BUS_A_ARADDR (BUS_A_ARADDR),
    .TRAN_s_axi_BUS_A_ARVALID (BUS_A_ARVALID),
    .TRAN_s_axi_BUS_A_ARREADY (BUS_A_ARREADY),
    .TRAN_s_axi_BUS_A_RVALID (BUS_A_RVALID),
    .TRAN_s_axi_BUS_A_RREADY (BUS_A_RREADY),
    .TRAN_s_axi_BUS_A_RDATA (BUS_A_RDATA),
    .TRAN_s_axi_BUS_A_RRESP (BUS_A_RRESP),
    .TRAN_s_axi_BUS_A_BVALID (BUS_A_BVALID),
    .TRAN_s_axi_BUS_A_BREADY (BUS_A_BREADY),
    .TRAN_s_axi_BUS_A_BRESP (BUS_A_BRESP),
    .TRAN_BUS_A_interrupt (BUS_A_INTERRUPT),
    .TRAN_BUS_A_read_data_finish(BUS_A_read_data_finish),
    .TRAN_BUS_A_write_data_finish(BUS_A_write_data_finish),
    .TRAN_BUS_A_ready_out (AESL_ready),
    .TRAN_BUS_A_ready_in (AESL_slave_ready),
    .TRAN_BUS_A_done_out (AESL_slave_output_done),
    .TRAN_BUS_A_idle_out (AESL_idle),
    .TRAN_BUS_A_write_start_in     (AESL_slave_write_start_in),
    .TRAN_BUS_A_write_start_finish (AESL_slave_write_start_finish),
    .TRAN_BUS_A_transaction_done_in (AESL_done_delay),
    .TRAN_BUS_A_start_in  (AESL_slave_start)
);

initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 1);
    while(AESL_ready_cnt != AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

    event next_trigger_ready_cnt;
    
    initial begin : gen_ready_cnt
        ready_cnt = 0;
        wait (AESL_reset === 1);
        forever begin
            @ (posedge AESL_clock);
            if (ready == 1) begin
                if (ready_cnt < AUTOTB_TRANSACTION_NUM) begin
                    ready_cnt = ready_cnt + 1;
                end
            end
            -> next_trigger_ready_cnt;
        end
    end
    
    wire all_finish = (done_cnt == AUTOTB_TRANSACTION_NUM);
    
    // done_cnt
    always @ (posedge AESL_clock) begin
        if (~AESL_reset) begin
            done_cnt <= 0;
        end else begin
            if (AESL_done == 1) begin
                if (done_cnt < AUTOTB_TRANSACTION_NUM) begin
                    done_cnt <= done_cnt + 1;
                end
            end
        end
    end
    
    initial begin : finish_simulation
        integer fp1;
        integer fp2;
        wait (all_finish == 1);
        // last transaction is saved at negedge right after last done
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_data_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_keep_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_strb_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_user_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_last_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_id_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat", "r");
    fp2 = $fopen("./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat\"!");
    else begin
        $display("Comparing rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat with impl_rtl.DuneDataCompressionCore.autotvout_mAxis_V_dest_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
        $display("Simulation Passed.");
        $finish;
    end
    
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end


reg end_sAxis_V_data_V;
reg [31:0] size_sAxis_V_data_V;
reg [31:0] size_sAxis_V_data_V_backup;
reg end_sAxis_V_keep_V;
reg [31:0] size_sAxis_V_keep_V;
reg [31:0] size_sAxis_V_keep_V_backup;
reg end_sAxis_V_strb_V;
reg [31:0] size_sAxis_V_strb_V;
reg [31:0] size_sAxis_V_strb_V_backup;
reg end_sAxis_V_user_V;
reg [31:0] size_sAxis_V_user_V;
reg [31:0] size_sAxis_V_user_V_backup;
reg end_sAxis_V_last_V;
reg [31:0] size_sAxis_V_last_V;
reg [31:0] size_sAxis_V_last_V_backup;
reg end_sAxis_V_id_V;
reg [31:0] size_sAxis_V_id_V;
reg [31:0] size_sAxis_V_id_V_backup;
reg end_sAxis_V_dest_V;
reg [31:0] size_sAxis_V_dest_V;
reg [31:0] size_sAxis_V_dest_V_backup;
reg end_mAxis_V_data_V;
reg [31:0] size_mAxis_V_data_V;
reg [31:0] size_mAxis_V_data_V_backup;
reg end_mAxis_V_keep_V;
reg [31:0] size_mAxis_V_keep_V;
reg [31:0] size_mAxis_V_keep_V_backup;
reg end_mAxis_V_strb_V;
reg [31:0] size_mAxis_V_strb_V;
reg [31:0] size_mAxis_V_strb_V_backup;
reg end_mAxis_V_user_V;
reg [31:0] size_mAxis_V_user_V;
reg [31:0] size_mAxis_V_user_V_backup;
reg end_mAxis_V_last_V;
reg [31:0] size_mAxis_V_last_V;
reg [31:0] size_mAxis_V_last_V_backup;
reg end_mAxis_V_id_V;
reg [31:0] size_mAxis_V_id_V;
reg [31:0] size_mAxis_V_id_V_backup;
reg end_mAxis_V_dest_V;
reg [31:0] size_mAxis_V_dest_V;
reg [31:0] size_mAxis_V_dest_V_backup;
reg end_config_init;
reg [31:0] size_config_init;
reg [31:0] size_config_init_backup;
reg end_config_mode;
reg [31:0] size_config_mode;
reg [31:0] size_config_mode_backup;
reg end_config_limit;
reg [31:0] size_config_limit;
reg [31:0] size_config_limit_backup;
reg end_monitor_common_pattern;
reg [31:0] size_monitor_common_pattern;
reg [31:0] size_monitor_common_pattern_backup;
reg end_monitor_cfg_m_mode;
reg [31:0] size_monitor_cfg_m_mode;
reg [31:0] size_monitor_cfg_m_mode_backup;
reg end_monitor_cfg_m_ncfgs;
reg [31:0] size_monitor_cfg_m_ncfgs;
reg [31:0] size_monitor_cfg_m_ncfgs_backup;
reg end_monitor_write_nbytes;
reg [31:0] size_monitor_write_nbytes;
reg [31:0] size_monitor_write_nbytes_backup;
reg end_monitor_write_npromoted;
reg [31:0] size_monitor_write_npromoted;
reg [31:0] size_monitor_write_npromoted_backup;
reg end_monitor_write_ndropped;
reg [31:0] size_monitor_write_ndropped;
reg [31:0] size_monitor_write_ndropped_backup;
reg end_monitor_write_npackets;
reg [31:0] size_monitor_write_npackets;
reg [31:0] size_monitor_write_npackets_backup;

initial begin : initial_process
    integer proc_rand;
    rst = 0;
    # 100;
    repeat(3) @ (posedge AESL_clock);
    rst = 1;
end
initial begin : start_process
    integer proc_rand;
    reg [31:0] start_cnt;
    ce = 1;
    start = 0;
    start_cnt = 0;
    wait (AESL_reset === 1);
    @ (posedge AESL_clock);
    #0 start = 1;
    start_cnt = start_cnt + 1;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt >= AUTOTB_TRANSACTION_NUM) begin
            // keep pushing garbage in
            #0 start = 1;
        end
        if (AESL_ready) begin
            start_cnt = start_cnt + 1;
        end
    end
end

always @(AESL_done)
begin
    tb_continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end
    
    initial begin : proc_gen_axis_internal_ready_sAxis
        sAxis_ready_reg = 0;
        @ (posedge ready_initial);
        forever begin
            @ (ap_c_n_tvin_trans_num_sAxis_V_data_V or sAxis_transaction);
            if (ap_c_n_tvin_trans_num_sAxis_V_data_V > sAxis_transaction) begin
                sAxis_ready_reg = 1;
            end else begin
                sAxis_ready_reg = 0;
            end
        end
    end
    
    `define STREAM_SIZE_IN_sAxis_V_data_V "./stream_size_in_sAxis_V_data_V.dat"
    
    initial begin : gen_ap_c_n_tvin_trans_num_sAxis_V_data_V
        integer fp_sAxis_V_data_V;
        reg [127:0] token_sAxis_V_data_V;
        integer ret;
        
        ap_c_n_tvin_trans_num_sAxis_V_data_V = 0;
        end_sAxis_V_data_V = 0;
        wait (AESL_reset === 1);
        
        fp_sAxis_V_data_V = $fopen(`STREAM_SIZE_IN_sAxis_V_data_V, "r");
        if(fp_sAxis_V_data_V == 0) begin
            $display("Failed to open file \"%s\"!", `STREAM_SIZE_IN_sAxis_V_data_V);
            $finish;
        end
        read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be [[[runtime]]]
        if (token_sAxis_V_data_V != "[[[runtime]]]") begin
            $display("ERROR: token_sAxis_V_data_V != \"[[[runtime]]]\"");
            $finish;
        end
        size_sAxis_V_data_V = 0;
        size_sAxis_V_data_V_backup = 0;
        while (size_sAxis_V_data_V == 0 && end_sAxis_V_data_V == 0) begin
            ap_c_n_tvin_trans_num_sAxis_V_data_V = ap_c_n_tvin_trans_num_sAxis_V_data_V + 1;
            read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be [[transaction]] or [[[/runtime]]]
            if (token_sAxis_V_data_V == "[[transaction]]") begin
                read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be transaction number
                read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be size for hls::stream
                ret = $sscanf(token_sAxis_V_data_V, "%d", size_sAxis_V_data_V);
                if (size_sAxis_V_data_V > 0) begin
                    size_sAxis_V_data_V_backup = size_sAxis_V_data_V;
                end
                read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be [[/transaction]]
            end else if (token_sAxis_V_data_V == "[[[/runtime]]]") begin
                $fclose(fp_sAxis_V_data_V);
                end_sAxis_V_data_V = 1;
            end else begin
                $display("ERROR: unknown token_sAxis_V_data_V");
                $finish;
            end
        end
        forever begin
            @ (posedge AESL_clock);
            if (end_sAxis_V_data_V == 0) begin
                if (sAxis_TREADY == 1) begin
                    if (size_sAxis_V_data_V > 0) begin
                        size_sAxis_V_data_V = size_sAxis_V_data_V - 1;
                        while (size_sAxis_V_data_V == 0 && end_sAxis_V_data_V == 0) begin
                            ap_c_n_tvin_trans_num_sAxis_V_data_V = ap_c_n_tvin_trans_num_sAxis_V_data_V + 1;
                            read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be [[transaction]] or [[[/runtime]]]
                            if (token_sAxis_V_data_V == "[[transaction]]") begin
                                read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be transaction number
                                read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be size for hls::stream
                                ret = $sscanf(token_sAxis_V_data_V, "%d", size_sAxis_V_data_V);
                                if (size_sAxis_V_data_V > 0) begin
                                    size_sAxis_V_data_V_backup = size_sAxis_V_data_V;
                                end
                                read_token(fp_sAxis_V_data_V, token_sAxis_V_data_V); // should be [[/transaction]]
                            end else if (token_sAxis_V_data_V == "[[[/runtime]]]") begin
                                size_sAxis_V_data_V = size_sAxis_V_data_V_backup;
                                $fclose(fp_sAxis_V_data_V);
                                end_sAxis_V_data_V = 1;
                            end else begin
                                $display("ERROR: unknown token_sAxis_V_data_V");
                                $finish;
                            end
                        end
                    end
                end
            end else begin
                if (sAxis_TREADY == 1) begin
                    if (size_sAxis_V_data_V > 0) begin
                        size_sAxis_V_data_V = size_sAxis_V_data_V - 1;
                        if (size_sAxis_V_data_V == 0) begin
                            ap_c_n_tvin_trans_num_sAxis_V_data_V = ap_c_n_tvin_trans_num_sAxis_V_data_V + 1;
                            size_sAxis_V_data_V = size_sAxis_V_data_V_backup;
                        end
                    end
                end
            end
        end
    end
    

reg dump_tvout_finish_mAxis_V_data_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_data_V
    integer fp;
    dump_tvout_finish_mAxis_V_data_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_data_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_data_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_data_V = 1;
end


reg dump_tvout_finish_mAxis_V_keep_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_keep_V
    integer fp;
    dump_tvout_finish_mAxis_V_keep_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_keep_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_keep_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_keep_V = 1;
end


reg dump_tvout_finish_mAxis_V_strb_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_strb_V
    integer fp;
    dump_tvout_finish_mAxis_V_strb_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_strb_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_strb_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_strb_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_strb_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_strb_V = 1;
end


reg dump_tvout_finish_mAxis_V_user_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_user_V
    integer fp;
    dump_tvout_finish_mAxis_V_user_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_user_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_user_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_user_V = 1;
end


reg dump_tvout_finish_mAxis_V_last_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_last_V
    integer fp;
    dump_tvout_finish_mAxis_V_last_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_last_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_last_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_last_V = 1;
end


reg dump_tvout_finish_mAxis_V_id_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_id_V
    integer fp;
    dump_tvout_finish_mAxis_V_id_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_id_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_id_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_id_V = 1;
end


reg dump_tvout_finish_mAxis_V_dest_V;

initial begin : dump_tvout_runtime_sign_mAxis_V_dest_V
    integer fp;
    dump_tvout_finish_mAxis_V_dest_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_dest_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_dest_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_mAxis_V_dest_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_mAxis_V_dest_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_mAxis_V_dest_V = 1;
end


reg dump_tvout_finish_monitor_common_pattern;

initial begin : dump_tvout_runtime_sign_monitor_common_pattern
    integer fp;
    dump_tvout_finish_monitor_common_pattern = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_common_pattern_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_common_pattern_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_common_pattern_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_common_pattern_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_common_pattern = 1;
end


reg dump_tvout_finish_monitor_cfg_m_mode;

initial begin : dump_tvout_runtime_sign_monitor_cfg_m_mode
    integer fp;
    dump_tvout_finish_monitor_cfg_m_mode = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_cfg_m_mode_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_cfg_m_mode_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_cfg_m_mode_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_cfg_m_mode_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_cfg_m_mode = 1;
end


reg dump_tvout_finish_monitor_cfg_m_ncfgs;

initial begin : dump_tvout_runtime_sign_monitor_cfg_m_ncfgs
    integer fp;
    dump_tvout_finish_monitor_cfg_m_ncfgs = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_cfg_m_ncfgs_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_cfg_m_ncfgs_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_cfg_m_ncfgs_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_cfg_m_ncfgs_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_cfg_m_ncfgs = 1;
end


reg dump_tvout_finish_monitor_write_nbytes;

initial begin : dump_tvout_runtime_sign_monitor_write_nbytes
    integer fp;
    dump_tvout_finish_monitor_write_nbytes = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_nbytes_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_nbytes_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_nbytes_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_nbytes_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_write_nbytes = 1;
end


reg dump_tvout_finish_monitor_write_npromoted;

initial begin : dump_tvout_runtime_sign_monitor_write_npromoted
    integer fp;
    dump_tvout_finish_monitor_write_npromoted = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_npromoted_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_npromoted_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_npromoted_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_npromoted_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_write_npromoted = 1;
end


reg dump_tvout_finish_monitor_write_ndropped;

initial begin : dump_tvout_runtime_sign_monitor_write_ndropped
    integer fp;
    dump_tvout_finish_monitor_write_ndropped = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_ndropped_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_ndropped_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_ndropped_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_ndropped_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_write_ndropped = 1;
end


reg dump_tvout_finish_monitor_write_npackets;

initial begin : dump_tvout_runtime_sign_monitor_write_npackets
    integer fp;
    dump_tvout_finish_monitor_write_npackets = 0;
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_npackets_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_npackets_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_monitor_write_npackets_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_monitor_write_npackets_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_monitor_write_npackets = 1;
end


////////////////////////////////////////////
// progress and performance
////////////////////////////////////////////

task wait_start();
    while (~AESL_start) begin
        @ (posedge AESL_clock);
    end
endtask

reg [31:0] clk_cnt = 0;
reg AESL_ready_p1;
reg AESL_start_p1;

always @ (posedge AESL_clock) begin
    clk_cnt <= clk_cnt + 1;
    AESL_ready_p1 <= AESL_ready;
    AESL_start_p1 <= AESL_start;
end

reg [31:0] start_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] start_cnt;
reg [31:0] ready_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] ap_ready_cnt;
reg [31:0] finish_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] finish_cnt;
event report_progress;

initial begin
    start_cnt = 0;
    finish_cnt = 0;
    ap_ready_cnt = 0;
    wait (AESL_reset == 1);
    wait_start();
    start_timestamp[start_cnt] = clk_cnt;
    start_cnt = start_cnt + 1;
    if (AESL_done) begin
        finish_timestamp[finish_cnt] = clk_cnt;
        finish_cnt = finish_cnt + 1;
    end
    -> report_progress;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt < AUTOTB_TRANSACTION_NUM) begin
            if ((AESL_start && AESL_ready_p1)||(AESL_start && ~AESL_start_p1)) begin
                start_timestamp[start_cnt] = clk_cnt;
                start_cnt = start_cnt + 1;
            end
        end
        if (ap_ready_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_start_p1 && AESL_ready_p1) begin
                ready_timestamp[ap_ready_cnt] = clk_cnt;
                ap_ready_cnt = ap_ready_cnt + 1;
            end
        end
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                finish_timestamp[finish_cnt] = clk_cnt;
                finish_cnt = finish_cnt + 1;
            end
        end
        -> report_progress;
    end
end

reg [31:0] progress_timeout;

initial begin : simulation_progress
    real intra_progress;
    wait (AESL_reset == 1);
    progress_timeout = PROGRESS_TIMEOUT;
    $display("////////////////////////////////////////////////////////////////////////////////////");
    $display("// Inter-Transaction Progress: Completed Transaction / Total Transaction");
    $display("// Intra-Transaction Progress: Measured Latency / Latency Estimation * 100%%");
    $display("//");
    $display("// RTL Simulation : \"Inter-Transaction Progress\" [\"Intra-Transaction Progress\"] @ \"Simulation Time\"");
    $display("////////////////////////////////////////////////////////////////////////////////////");
    print_progress();
    while (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
        @ (report_progress);
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                print_progress();
                progress_timeout = PROGRESS_TIMEOUT;
            end else begin
                if (progress_timeout == 0) begin
                    print_progress();
                    progress_timeout = PROGRESS_TIMEOUT;
                end else begin
                    progress_timeout = progress_timeout - 1;
                end
            end
        end
    end
    print_progress();
    $display("////////////////////////////////////////////////////////////////////////////////////");
    calculate_performance();
end

task get_intra_progress(output real intra_progress);
    begin
        if (start_cnt > finish_cnt) begin
            intra_progress = clk_cnt - start_timestamp[finish_cnt];
        end else if(finish_cnt > 0) begin
            intra_progress = LATENCY_ESTIMATION;
        end else begin
            intra_progress = 0;
        end
        intra_progress = intra_progress / LATENCY_ESTIMATION;
    end
endtask

task print_progress();
    real intra_progress;
    begin
        if (LATENCY_ESTIMATION > 0) begin
            get_intra_progress(intra_progress);
            $display("// RTL Simulation : %0d / %0d [%2.2f%%] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, intra_progress * 100, $time);
        end else begin
            $display("// RTL Simulation : %0d / %0d [n/a] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, $time);
        end
    end
endtask

task calculate_performance();
    integer i;
    integer fp;
    reg [31:0] latency [0:AUTOTB_TRANSACTION_NUM - 1];
    reg [31:0] latency_min;
    reg [31:0] latency_max;
    reg [31:0] latency_total;
    reg [31:0] latency_average;
    reg [31:0] interval [0:AUTOTB_TRANSACTION_NUM - 2];
    reg [31:0] interval_min;
    reg [31:0] interval_max;
    reg [31:0] interval_total;
    reg [31:0] interval_average;
    begin
        latency_min = -1;
        latency_max = 0;
        latency_total = 0;
        interval_min = -1;
        interval_max = 0;
        interval_total = 0;

        for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
            // calculate latency
            latency[i] = finish_timestamp[i] - start_timestamp[i];
            if (latency[i] > latency_max) latency_max = latency[i];
            if (latency[i] < latency_min) latency_min = latency[i];
            latency_total = latency_total + latency[i];
            // calculate interval
            if (AUTOTB_TRANSACTION_NUM == 1) begin
                interval[i] = 0;
                interval_max = 0;
                interval_min = 0;
                interval_total = 0;
            end else if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                interval[i] = start_timestamp[i + 1] - start_timestamp[i];
                if (interval[i] > interval_max) interval_max = interval[i];
                if (interval[i] < interval_min) interval_min = interval[i];
                interval_total = interval_total + interval[i];
            end
        end

        latency_average = latency_total / AUTOTB_TRANSACTION_NUM;
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            interval_average = 0;
        end else begin
            interval_average = interval_total / (AUTOTB_TRANSACTION_NUM - 1);
        end

        fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

        $fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latency_max);
        $fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latency_min);
        $fdisplay(fp, "$AVER_LATENCY = \"%0d\"", latency_average);
        $fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", interval_max);
        $fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", interval_min);
        $fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", interval_average);

        $fclose(fp);

        fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");

        $fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            i = 0;
            $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
        end else begin
            for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
                if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                    $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
                end else begin
                    $fdisplay(fp, "transaction%8d:%16d               x", i, latency[i]);
                end
            end
        end

        $fclose(fp);
    end
endtask


////////////////////////////////////////////
// Dependence Check
////////////////////////////////////////////

`ifndef POST_SYN

`endif

endmodule
