export GIT_BYPASS = 1

# define firmware version
export PRJ_VERSION = 0x00000055

#       DATE    VERSION WHO  DESCRITPTION
# ---------- ---------- ---  -------------------------------------------------
# 2018/09/06 0x00000055 jjr  Incorporates the setting of the timing endpoint
#                            address.


# Define target output
target: bit

# Define target part
export PRJ_PART = XC7Z030FBG484-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
