export GIT_BYPASS = 1

# define firmware version
export PRJ_VERSION = 0x00000004

# Define target output
target: bit

# Define target part
export PRJ_PART = XC7Z030FBG484-2

# If REMOVE_UNUSED_CODE = 0, all source code is kept after importing to Vivado project
# If REMOVE_UNUSED_CODE = 1, all unused source code is removed from Vivado project
export REMOVE_UNUSED_CODE = 1

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
