# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/APE_encode150.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/APE_encode150_tabbFp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/APE_encode151.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/APE_encode152.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/APE_encode153.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/Block_proc.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/Block_proc203.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/Block_proc204.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibGp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibHp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibIp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibJp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibKp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibLp.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressibPq.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressionC_1.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressionC_2.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressionCore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressionCore_BUS_A_s_axi.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/acquire_packet.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/copy.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/dataflow_in_loop_ACQ.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/dataflow_in_loop_bDo.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/dataflow_in_loop_bDo_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/encode4.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/encode4_entry211.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w10_d2_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w1_d2_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w32_d2_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w32_d2_A_x.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w32_d2_A_x_x.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w32_d2_A_x_x_x.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w32_d3_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w4_d2_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w5_d2_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w5_d2_A_x.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w64_d2_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w64_d2_A_x.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w64_d3_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/fifo_w7_d3_A.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpb1s.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpb1s_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcFz.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcFz_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcGz.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcGz_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpchv.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpchv_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcpw.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcpw_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcxx.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_cmpcxx_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_pktb0s.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_pktb0s_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_pktbZs.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/handle_packet_pktbZs_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisbkb.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisbkb_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisbll.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisbll_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisbml.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisbml_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hiscud.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hiscud_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_HisdEe.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_HisdEe_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisg8j.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisg8j_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisibs.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_Hisibs_ram.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_PrvHfu.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_frame_adcbBo.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/process_packet.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/read208.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/start_for_Block_peSV.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/start_for_DuneDateRU.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/update.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/writeN.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_adcs4.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_adcs4_contabQq.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_adcs4_contabQq_memcore.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_adcs4_entry217.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_packet.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_packet_offsbYs.v
  /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/write_r.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressionCore.xdc
set_property used_in_implementation false [get_files /u1/rherbst/build/DuneDataCompression/DuneDataCompression_project/solution1/impl/verilog/DuneDataCompressionCore.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top DuneDataCompressionCore -part xc7z045ffg900-2 -no_iobuf -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DuneDataCompressionCore.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DuneDataCompressionCore_utilization_synth.rpt -pb DuneDataCompressionCore_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
