
# Define target output
target: vcs

export PRJ_VERSION = 0xDA100416

export GIT_BYPASS  = 1

# Define target part
export PRJ_PART = XC7Z045FFG900-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk

