// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DuneDataCompressionC_1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        config_init_dout,
        config_init_empty_n,
        config_init_read,
        config_mode_dout,
        config_mode_empty_n,
        config_mode_read,
        config_limit_dout,
        config_limit_empty_n,
        config_limit_read,
        config_init_out_din,
        config_init_out_full_n,
        config_init_out_write,
        config_mode_out_din,
        config_mode_out_full_n,
        config_mode_out_write,
        config_limit_out_din,
        config_limit_out_full_n,
        config_limit_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] config_init_dout;
input   config_init_empty_n;
output   config_init_read;
input  [31:0] config_mode_dout;
input   config_mode_empty_n;
output   config_mode_read;
input  [31:0] config_limit_dout;
input   config_limit_empty_n;
output   config_limit_read;
output  [31:0] config_init_out_din;
input   config_init_out_full_n;
output   config_init_out_write;
output  [31:0] config_mode_out_din;
input   config_mode_out_full_n;
output   config_mode_out_write;
output  [31:0] config_limit_out_din;
input   config_limit_out_full_n;
output   config_limit_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg config_init_read;
reg config_mode_read;
reg config_limit_read;
reg config_init_out_write;
reg config_mode_out_write;
reg config_limit_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    config_init_blk_n;
reg    config_mode_blk_n;
reg    config_limit_blk_n;
reg    config_init_out_blk_n;
reg    config_mode_out_blk_n;
reg    config_limit_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_init_blk_n = config_init_empty_n;
    end else begin
        config_init_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_init_out_blk_n = config_init_out_full_n;
    end else begin
        config_init_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_init_out_write = 1'b1;
    end else begin
        config_init_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_init_read = 1'b1;
    end else begin
        config_init_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_limit_blk_n = config_limit_empty_n;
    end else begin
        config_limit_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_limit_out_blk_n = config_limit_out_full_n;
    end else begin
        config_limit_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_limit_out_write = 1'b1;
    end else begin
        config_limit_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_limit_read = 1'b1;
    end else begin
        config_limit_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_mode_blk_n = config_mode_empty_n;
    end else begin
        config_mode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_mode_out_blk_n = config_mode_out_full_n;
    end else begin
        config_mode_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_mode_out_write = 1'b1;
    end else begin
        config_mode_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_mode_read = 1'b1;
    end else begin
        config_mode_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (config_limit_out_full_n == 1'b0) | (config_mode_out_full_n == 1'b0) | (config_init_out_full_n == 1'b0) | (config_limit_empty_n == 1'b0) | (config_mode_empty_n == 1'b0) | (config_init_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign config_init_out_din = config_init_dout;

assign config_limit_out_din = config_limit_dout;

assign config_mode_out_din = config_mode_dout;

assign start_out = real_start;

endmodule //DuneDataCompressionC_1
