#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.1
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

/afs/slac.stanford.edu/g/reseng/xilinx/vivado_2018.1/Vivado/2018.1/bin/vivado  -notrace -mode batch -source run_vivado.tcl || exit $?


