// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module read196 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        frame_m_dat_d_0_address1,
        frame_m_dat_d_0_ce1,
        frame_m_dat_d_0_we1,
        frame_m_dat_d_0_d1,
        frame_m_dat_d_1_address1,
        frame_m_dat_d_1_ce1,
        frame_m_dat_d_1_we1,
        frame_m_dat_d_1_d1,
        sAxis_TDATA,
        sAxis_TVALID,
        sAxis_TREADY,
        sAxis_TKEEP,
        sAxis_TSTRB,
        sAxis_TUSER,
        sAxis_TLAST,
        sAxis_TID,
        sAxis_TDEST,
        iframe_assign,
        iframe_assign_c_din,
        iframe_assign_c_full_n,
        iframe_assign_c_write,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [3:0] frame_m_dat_d_0_address1;
output   frame_m_dat_d_0_ce1;
output   frame_m_dat_d_0_we1;
output  [63:0] frame_m_dat_d_0_d1;
output  [3:0] frame_m_dat_d_1_address1;
output   frame_m_dat_d_1_ce1;
output   frame_m_dat_d_1_we1;
output  [63:0] frame_m_dat_d_1_d1;
input  [63:0] sAxis_TDATA;
input   sAxis_TVALID;
output   sAxis_TREADY;
input  [7:0] sAxis_TKEEP;
input  [7:0] sAxis_TSTRB;
input  [3:0] sAxis_TUSER;
input  [0:0] sAxis_TLAST;
input  [0:0] sAxis_TID;
input  [0:0] sAxis_TDEST;
input  [10:0] iframe_assign;
output  [9:0] iframe_assign_c_din;
input   iframe_assign_c_full_n;
output   iframe_assign_c_write;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] frame_m_dat_d_0_address1;
reg frame_m_dat_d_0_ce1;
reg frame_m_dat_d_0_we1;
reg[3:0] frame_m_dat_d_1_address1;
reg frame_m_dat_d_1_ce1;
reg frame_m_dat_d_1_we1;
reg iframe_assign_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] sAxis_V_data_V_0_data_out;
wire    sAxis_V_data_V_0_vld_in;
wire    sAxis_V_data_V_0_vld_out;
wire    sAxis_V_data_V_0_ack_in;
reg    sAxis_V_data_V_0_ack_out;
reg   [63:0] sAxis_V_data_V_0_payload_A;
reg   [63:0] sAxis_V_data_V_0_payload_B;
reg    sAxis_V_data_V_0_sel_rd;
reg    sAxis_V_data_V_0_sel_wr;
wire    sAxis_V_data_V_0_sel;
wire    sAxis_V_data_V_0_load_A;
wire    sAxis_V_data_V_0_load_B;
reg   [1:0] sAxis_V_data_V_0_state;
wire    sAxis_V_data_V_0_state_cmp_full;
reg   [3:0] sAxis_V_user_V_0_data_out;
wire    sAxis_V_user_V_0_vld_in;
wire    sAxis_V_user_V_0_vld_out;
wire    sAxis_V_user_V_0_ack_in;
reg    sAxis_V_user_V_0_ack_out;
reg   [3:0] sAxis_V_user_V_0_payload_A;
reg   [3:0] sAxis_V_user_V_0_payload_B;
reg    sAxis_V_user_V_0_sel_rd;
reg    sAxis_V_user_V_0_sel_wr;
wire    sAxis_V_user_V_0_sel;
wire    sAxis_V_user_V_0_load_A;
wire    sAxis_V_user_V_0_load_B;
reg   [1:0] sAxis_V_user_V_0_state;
wire    sAxis_V_user_V_0_state_cmp_full;
reg   [0:0] sAxis_V_last_V_0_data_out;
wire    sAxis_V_last_V_0_vld_in;
wire    sAxis_V_last_V_0_vld_out;
wire    sAxis_V_last_V_0_ack_in;
reg    sAxis_V_last_V_0_ack_out;
reg   [0:0] sAxis_V_last_V_0_payload_A;
reg   [0:0] sAxis_V_last_V_0_payload_B;
reg    sAxis_V_last_V_0_sel_rd;
reg    sAxis_V_last_V_0_sel_wr;
wire    sAxis_V_last_V_0_sel;
wire    sAxis_V_last_V_0_load_A;
wire    sAxis_V_last_V_0_load_B;
reg   [1:0] sAxis_V_last_V_0_state;
wire    sAxis_V_last_V_0_state_cmp_full;
wire    sAxis_V_dest_V_0_vld_in;
reg    sAxis_V_dest_V_0_ack_out;
reg   [1:0] sAxis_V_dest_V_0_state;
reg   [0:0] ctx_first;
reg   [9:0] ctx_wibId_V;
reg   [63:0] ctx_hdrs_V_1;
reg   [15:0] ctx_cvtCnt0;
reg   [63:0] ctx_hdrs_V_3;
reg   [15:0] ctx_cvtCnt1;
reg   [63:0] ctx_hdrs_V_5;
reg    sAxis_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
reg   [0:0] tmp_379_i_i_i_reg_1578;
reg    iframe_assign_c_blk_n;
wire   [31:0] p_Val2_3_fu_586_p3;
reg   [31:0] p_Val2_3_reg_1494;
reg    ap_block_state2;
wire   [0:0] wibErrCommaChar_fu_624_p2;
reg   [0:0] wibErrCommaChar_reg_1502;
wire   [0:0] wibErrVersion_fu_640_p2;
reg   [0:0] wibErrVersion_reg_1507;
reg   [9:0] tmp_323_cast_i_i_i_reg_1512;
wire   [0:0] wibErrRsvd_fu_666_p2;
reg   [0:0] wibErrRsvd_reg_1517;
wire   [0:0] wibErrErrors_fu_672_p2;
reg   [0:0] wibErrErrors_reg_1522;
reg   [31:0] p_Result_5_fu_770_p4;
reg   [31:0] p_Result_5_reg_1527;
reg   [31:0] status_V_45_fu_892_p4;
reg   [31:0] status_V_45_reg_1533;
reg   [31:0] status_V_17_fu_1008_p4;
wire   [3:0] idx_fu_1030_p2;
reg   [3:0] idx_reg_1548;
wire    ap_CS_fsm_state6;
wire   [31:0] status_V_32_fu_1098_p3;
wire   [31:0] status_V_33_fu_1106_p3;
reg   [31:0] status_V_49_fu_1216_p4;
reg   [31:0] status_V_49_reg_1566;
reg   [31:0] status_V_27_fu_1332_p4;
wire   [0:0] tmp_379_i_i_i_fu_1348_p2;
wire    ap_CS_fsm_state10;
wire   [3:0] idx_1_fu_1354_p2;
reg   [3:0] idx_1_reg_1582;
wire   [31:0] status_V_40_fu_1418_p3;
reg    ap_block_state11;
wire   [0:0] p_not_i_i_i_i_i_i_fu_1402_p2;
wire   [31:0] status_V_41_fu_1426_p3;
reg   [31:0] p_Val2_27_reg_335;
reg   [31:0] p_Val2_19_reg_345;
reg   [3:0] idx_0_i_i43_i_i_i_i_reg_355;
reg   [31:0] p_Val2_31_reg_367;
reg   [31:0] p_Val2_i2_0_i10_i_s_reg_377;
reg   [3:0] idx_0_i_i_i_i_i_i_reg_387;
reg   [31:0] ap_phi_mux_p_Val2_34_phi_fu_402_p4;
wire   [0:0] grp_fu_441_p3;
reg   [31:0] p_Result_16_fu_1390_p4;
reg   [31:0] ap_phi_mux_p_Val2_32_phi_fu_412_p4;
reg   [31:0] p_Result_20_fu_1483_p4;
reg   [31:0] ap_phi_mux_ReadFrame_m_status_V_phi_fu_422_p6;
reg   [31:0] ReadFrame_m_status_V_reg_419;
wire   [0:0] tmp_84_fu_1442_p1;
wire   [31:0] status_V_52_fu_1474_p3;
wire   [63:0] newIndex10_cast_i_i_s_fu_1056_p1;
wire   [63:0] newIndex_cast_i_i_i_fu_1384_p1;
wire   [0:0] ctx_first_load_load_fu_594_p1;
wire   [63:0] tmp_331_i_i_i_fu_780_p2;
wire   [15:0] grp_fu_491_p2;
wire   [0:0] tmp_76_fu_1042_p1;
wire   [0:0] tmp_77_fu_1370_p1;
wire   [3:0] grp_fu_459_p4;
wire   [7:0] grp_fu_475_p4;
wire   [15:0] grp_fu_449_p4;
wire   [15:0] grp_fu_507_p4;
wire   [26:0] p_Val2_18_cast_i_i_fu_536_p3;
wire   [31:0] p_Result_s_fu_552_p3;
wire   [31:0] p_Val2_18_cast_i_i_1_fu_544_p3;
wire   [31:0] p_Val2_2_fu_560_p3;
wire   [0:0] tmp_53_fu_568_p3;
reg   [31:0] p_Result_1_fu_576_p4;
wire   [7:0] tmp_55_fu_620_p1;
wire   [4:0] tmp_320_cast_i_i_i_fu_630_p4;
wire   [23:0] tmp_327_cast_i_i_i_fu_656_p4;
wire   [0:0] wibErrId_fu_682_p2;
wire   [4:0] tmp_i_i_i_fu_687_p6;
wire   [31:0] p_Result_2_fu_697_p5;
wire   [0:0] tmp_56_fu_716_p3;
reg   [31:0] p_Result_3_fu_724_p4;
wire   [31:0] status_V_fu_734_p3;
reg   [31:0] p_Result_4_fu_742_p4;
wire   [31:0] status_V_43_fu_752_p3;
wire   [0:0] wibErrTimestamp_fu_764_p2;
wire   [0:0] tmp_60_fu_800_p3;
reg   [31:0] p_Result_6_fu_808_p4;
wire   [31:0] status_V_44_fu_817_p3;
reg   [31:0] p_Result_7_fu_824_p4;
wire   [3:0] tmp_63_fu_846_p1;
wire   [31:0] status_V_11_fu_834_p3;
wire   [0:0] cdErrStreamErr1_fu_850_p2;
reg   [31:0] tmp_341_i_i_i_fu_862_p4;
wire   [0:0] grp_fu_469_p2;
reg   [31:0] tmp_342_i_i_i_fu_872_p4;
wire   [0:0] grp_fu_485_p2;
reg   [31:0] tmp_343_i_i_i_fu_882_p4;
wire   [0:0] cdErrCvtCnt_fu_856_p2;
wire   [0:0] tmp_64_fu_916_p3;
reg   [31:0] p_Result_8_fu_924_p4;
wire   [31:0] status_V_46_fu_933_p3;
reg   [31:0] p_Result_9_fu_940_p4;
wire   [15:0] tmp_67_fu_962_p1;
wire   [31:0] grp_fu_497_p4;
wire   [31:0] tmp_350_i_i_i_fu_972_p4;
wire   [31:0] status_V_16_fu_950_p3;
wire   [0:0] cdErrErrReg_fu_966_p2;
reg   [31:0] tmp_353_i_i_i_fu_988_p4;
wire   [0:0] grp_fu_517_p2;
reg   [31:0] tmp_354_i_i_i_fu_998_p4;
wire   [0:0] cdErrHdrs_fu_982_p2;
wire   [3:0] p_sum1_i_i_i_fu_1036_p2;
wire   [2:0] newIndex10_i_i_i_fu_1046_p4;
reg   [31:0] p_Result_10_fu_1062_p4;
wire   [31:0] status_V_47_fu_1072_p3;
reg   [31:0] p_Result_11_fu_1088_p4;
wire   [31:0] status_V_30_fu_1080_p3;
wire   [0:0] tmp_68_fu_1122_p3;
reg   [31:0] p_Result_12_fu_1130_p4;
wire   [31:0] status_V_48_fu_1140_p3;
reg   [31:0] p_Result_13_fu_1148_p4;
wire   [3:0] tmp_71_fu_1170_p1;
wire   [31:0] status_V_21_fu_1158_p3;
wire   [0:0] cdErrStreamErr1_1_fu_1174_p2;
reg   [31:0] tmp_365_i_i_i_fu_1186_p4;
reg   [31:0] tmp_366_i_i_i_fu_1196_p4;
reg   [31:0] tmp_367_i_i_i_fu_1206_p4;
wire   [0:0] cdErrCvtCnt_1_fu_1180_p2;
wire   [0:0] tmp_72_fu_1240_p3;
reg   [31:0] p_Result_14_fu_1248_p4;
wire   [31:0] status_V_50_fu_1257_p3;
reg   [31:0] p_Result_15_fu_1264_p4;
wire   [15:0] tmp_75_fu_1286_p1;
wire   [31:0] tmp_374_i_i_i_fu_1296_p4;
wire   [31:0] status_V_26_fu_1274_p3;
wire   [0:0] cdErrErrReg_1_fu_1290_p2;
reg   [31:0] tmp_377_i_i_i_fu_1312_p4;
reg   [31:0] tmp_378_i_i_i_fu_1322_p4;
wire   [0:0] cdErrHdrs_1_fu_1306_p2;
wire   [4:0] tmp_380_cast_i_i_i_fu_1360_p1;
wire   [4:0] p_sum_i_i_i_fu_1364_p2;
wire   [3:0] newIndex_i_i_i_fu_1374_p4;
reg   [31:0] p_Result_17_fu_1408_p4;
wire   [0:0] tmp_83_fu_1434_p3;
reg   [31:0] p_Result_18_fu_1446_p4;
wire   [31:0] status_V_51_fu_1456_p3;
reg   [31:0] p_Result_19_fu_1464_p4;
wire   [0:0] exitcond_i_i_i_fu_1024_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_condition_1423;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 sAxis_V_data_V_0_payload_A = 64'd0;
#0 sAxis_V_data_V_0_payload_B = 64'd0;
#0 sAxis_V_data_V_0_sel_rd = 1'b0;
#0 sAxis_V_data_V_0_sel_wr = 1'b0;
#0 sAxis_V_data_V_0_state = 2'd0;
#0 sAxis_V_user_V_0_payload_A = 4'd0;
#0 sAxis_V_user_V_0_payload_B = 4'd0;
#0 sAxis_V_user_V_0_sel_rd = 1'b0;
#0 sAxis_V_user_V_0_sel_wr = 1'b0;
#0 sAxis_V_user_V_0_state = 2'd0;
#0 sAxis_V_last_V_0_payload_A = 1'd0;
#0 sAxis_V_last_V_0_payload_B = 1'd0;
#0 sAxis_V_last_V_0_sel_rd = 1'b0;
#0 sAxis_V_last_V_0_sel_wr = 1'b0;
#0 sAxis_V_last_V_0_state = 2'd0;
#0 sAxis_V_dest_V_0_state = 2'd0;
#0 ctx_first = 1'd1;
#0 ctx_wibId_V = 10'd0;
#0 ctx_hdrs_V_1 = 64'd0;
#0 ctx_cvtCnt0 = 16'd0;
#0 ctx_hdrs_V_3 = 64'd0;
#0 ctx_cvtCnt1 = 16'd0;
#0 ctx_hdrs_V_5 = 64'd0;
#0 tmp_379_i_i_i_reg_1578 = 1'd0;
#0 p_Val2_3_reg_1494 = 32'd0;
#0 wibErrCommaChar_reg_1502 = 1'd0;
#0 wibErrVersion_reg_1507 = 1'd0;
#0 tmp_323_cast_i_i_i_reg_1512 = 10'd0;
#0 wibErrRsvd_reg_1517 = 1'd0;
#0 wibErrErrors_reg_1522 = 1'd0;
#0 p_Result_5_reg_1527 = 32'd0;
#0 status_V_45_reg_1533 = 32'd0;
#0 idx_reg_1548 = 4'd0;
#0 status_V_49_reg_1566 = 32'd0;
#0 idx_1_reg_1582 = 4'd0;
#0 p_Val2_27_reg_335 = 32'd0;
#0 p_Val2_19_reg_345 = 32'd0;
#0 idx_0_i_i43_i_i_i_i_reg_355 = 4'd0;
#0 p_Val2_31_reg_367 = 32'd0;
#0 p_Val2_i2_0_i10_i_s_reg_377 = 32'd0;
#0 idx_0_i_i_i_i_i_i_reg_387 = 4'd0;
#0 ReadFrame_m_status_V_reg_419 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ReadFrame_m_status_V_reg_419 <= 32'd0;
    end else begin
        if (((tmp_379_i_i_i_fu_1348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
            ReadFrame_m_status_V_reg_419 <= p_Val2_i2_0_i10_i_s_reg_377;
        end else if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (tmp_84_fu_1442_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            ReadFrame_m_status_V_reg_419 <= status_V_52_fu_1474_p3;
        end else if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_84_fu_1442_p1 == 1'd1) & (p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
            ReadFrame_m_status_V_reg_419 <= p_Result_20_fu_1483_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state11) & ((p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) | (tmp_379_i_i_i_reg_1578 == 1'd0)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_cvtCnt0 <= 16'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ctx_cvtCnt0 <= grp_fu_491_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_cvtCnt1 <= 16'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
            ctx_cvtCnt1 <= grp_fu_491_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_first <= 1'd1;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (ctx_first_load_load_fu_594_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ctx_first <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_hdrs_V_1 <= 64'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ctx_hdrs_V_1 <= tmp_331_i_i_i_fu_780_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_hdrs_V_3 <= 64'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ctx_hdrs_V_3 <= sAxis_V_data_V_0_data_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_hdrs_V_5 <= 64'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ctx_hdrs_V_5 <= sAxis_V_data_V_0_data_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ctx_wibId_V <= 10'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (ctx_first_load_load_fu_594_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ctx_wibId_V <= {{sAxis_V_data_V_0_data_out[21:12]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        idx_0_i_i43_i_i_i_i_reg_355 <= 4'd0;
    end else begin
        if ((sAxis_V_data_V_0_vld_out == 1'b1)) begin
            if ((1'b1 == ap_CS_fsm_state7)) begin
                idx_0_i_i43_i_i_i_i_reg_355 <= idx_reg_1548;
            end else if ((1'b1 == ap_CS_fsm_state5)) begin
                idx_0_i_i43_i_i_i_i_reg_355 <= 4'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        idx_0_i_i_i_i_i_i_reg_387 <= 4'd0;
    end else begin
        if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            idx_0_i_i_i_i_i_i_reg_387 <= idx_1_reg_1582;
        end else if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            idx_0_i_i_i_i_i_i_reg_387 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        idx_1_reg_1582 <= 4'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            idx_1_reg_1582 <= idx_1_fu_1354_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        idx_reg_1548 <= 4'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            idx_reg_1548 <= idx_fu_1030_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Result_5_reg_1527 <= 32'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            p_Result_5_reg_1527 <= p_Result_5_fu_770_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Val2_19_reg_345 <= 32'd0;
    end else begin
        if ((sAxis_V_data_V_0_vld_out == 1'b1)) begin
            if ((1'b1 == ap_CS_fsm_state7)) begin
                p_Val2_19_reg_345 <= status_V_33_fu_1106_p3;
            end else if ((1'b1 == ap_CS_fsm_state5)) begin
                p_Val2_19_reg_345 <= status_V_17_fu_1008_p4;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Val2_27_reg_335 <= 32'd0;
    end else begin
        if ((sAxis_V_data_V_0_vld_out == 1'b1)) begin
            if ((1'b1 == ap_CS_fsm_state7)) begin
                p_Val2_27_reg_335 <= status_V_32_fu_1098_p3;
            end else if ((1'b1 == ap_CS_fsm_state5)) begin
                p_Val2_27_reg_335 <= status_V_17_fu_1008_p4;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Val2_31_reg_367 <= 32'd0;
    end else begin
        if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            p_Val2_31_reg_367 <= status_V_40_fu_1418_p3;
        end else if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            p_Val2_31_reg_367 <= status_V_27_fu_1332_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Val2_3_reg_1494 <= 32'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            p_Val2_3_reg_1494 <= p_Val2_3_fu_586_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Val2_i2_0_i10_i_s_reg_377 <= 32'd0;
    end else begin
        if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            p_Val2_i2_0_i10_i_s_reg_377 <= status_V_41_fu_1426_p3;
        end else if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            p_Val2_i2_0_i10_i_s_reg_377 <= status_V_27_fu_1332_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_data_V_0_payload_A <= 64'd0;
    end else begin
        if ((sAxis_V_data_V_0_load_A == 1'b1)) begin
            sAxis_V_data_V_0_payload_A <= sAxis_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_data_V_0_payload_B <= 64'd0;
    end else begin
        if ((sAxis_V_data_V_0_load_B == 1'b1)) begin
            sAxis_V_data_V_0_payload_B <= sAxis_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((sAxis_V_data_V_0_ack_out == 1'b1) & (sAxis_V_data_V_0_vld_out == 1'b1))) begin
            sAxis_V_data_V_0_sel_rd <= ~sAxis_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((sAxis_V_data_V_0_ack_in == 1'b1) & (sAxis_V_data_V_0_vld_in == 1'b1))) begin
            sAxis_V_data_V_0_sel_wr <= ~sAxis_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((sAxis_V_data_V_0_state == 2'd2) & (sAxis_V_data_V_0_vld_in == 1'b0)) | ((sAxis_V_data_V_0_state == 2'd3) & (sAxis_V_data_V_0_vld_in == 1'b0) & (sAxis_V_data_V_0_ack_out == 1'b1)))) begin
            sAxis_V_data_V_0_state <= 2'd2;
        end else if ((((sAxis_V_data_V_0_state == 2'd1) & (sAxis_V_data_V_0_ack_out == 1'b0)) | ((sAxis_V_data_V_0_state == 2'd3) & (sAxis_V_data_V_0_ack_out == 1'b0) & (sAxis_V_data_V_0_vld_in == 1'b1)))) begin
            sAxis_V_data_V_0_state <= 2'd1;
        end else if (((~((sAxis_V_data_V_0_vld_in == 1'b0) & (sAxis_V_data_V_0_ack_out == 1'b1)) & ~((sAxis_V_data_V_0_ack_out == 1'b0) & (sAxis_V_data_V_0_vld_in == 1'b1)) & (sAxis_V_data_V_0_state == 2'd3)) | ((sAxis_V_data_V_0_state == 2'd1) & (sAxis_V_data_V_0_ack_out == 1'b1)) | ((sAxis_V_data_V_0_state == 2'd2) & (sAxis_V_data_V_0_vld_in == 1'b1)))) begin
            sAxis_V_data_V_0_state <= 2'd3;
        end else begin
            sAxis_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((sAxis_V_dest_V_0_state == 2'd2) & (sAxis_V_dest_V_0_vld_in == 1'b0)) | ((sAxis_V_dest_V_0_state == 2'd3) & (sAxis_V_dest_V_0_vld_in == 1'b0) & (sAxis_V_dest_V_0_ack_out == 1'b1)))) begin
            sAxis_V_dest_V_0_state <= 2'd2;
        end else if ((((sAxis_V_dest_V_0_state == 2'd1) & (sAxis_V_dest_V_0_ack_out == 1'b0)) | ((sAxis_V_dest_V_0_state == 2'd3) & (sAxis_V_dest_V_0_ack_out == 1'b0) & (sAxis_V_dest_V_0_vld_in == 1'b1)))) begin
            sAxis_V_dest_V_0_state <= 2'd1;
        end else if (((~((sAxis_V_dest_V_0_vld_in == 1'b0) & (sAxis_V_dest_V_0_ack_out == 1'b1)) & ~((sAxis_V_dest_V_0_ack_out == 1'b0) & (sAxis_V_dest_V_0_vld_in == 1'b1)) & (sAxis_V_dest_V_0_state == 2'd3)) | ((sAxis_V_dest_V_0_state == 2'd1) & (sAxis_V_dest_V_0_ack_out == 1'b1)) | ((sAxis_V_dest_V_0_state == 2'd2) & (sAxis_V_dest_V_0_vld_in == 1'b1)))) begin
            sAxis_V_dest_V_0_state <= 2'd3;
        end else begin
            sAxis_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_last_V_0_payload_A <= 1'd0;
    end else begin
        if ((sAxis_V_last_V_0_load_A == 1'b1)) begin
            sAxis_V_last_V_0_payload_A <= sAxis_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_last_V_0_payload_B <= 1'd0;
    end else begin
        if ((sAxis_V_last_V_0_load_B == 1'b1)) begin
            sAxis_V_last_V_0_payload_B <= sAxis_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((sAxis_V_last_V_0_ack_out == 1'b1) & (sAxis_V_last_V_0_vld_out == 1'b1))) begin
            sAxis_V_last_V_0_sel_rd <= ~sAxis_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((sAxis_V_last_V_0_ack_in == 1'b1) & (sAxis_V_last_V_0_vld_in == 1'b1))) begin
            sAxis_V_last_V_0_sel_wr <= ~sAxis_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((sAxis_V_last_V_0_state == 2'd2) & (sAxis_V_last_V_0_vld_in == 1'b0)) | ((sAxis_V_last_V_0_state == 2'd3) & (sAxis_V_last_V_0_vld_in == 1'b0) & (sAxis_V_last_V_0_ack_out == 1'b1)))) begin
            sAxis_V_last_V_0_state <= 2'd2;
        end else if ((((sAxis_V_last_V_0_state == 2'd1) & (sAxis_V_last_V_0_ack_out == 1'b0)) | ((sAxis_V_last_V_0_state == 2'd3) & (sAxis_V_last_V_0_ack_out == 1'b0) & (sAxis_V_last_V_0_vld_in == 1'b1)))) begin
            sAxis_V_last_V_0_state <= 2'd1;
        end else if (((~((sAxis_V_last_V_0_vld_in == 1'b0) & (sAxis_V_last_V_0_ack_out == 1'b1)) & ~((sAxis_V_last_V_0_ack_out == 1'b0) & (sAxis_V_last_V_0_vld_in == 1'b1)) & (sAxis_V_last_V_0_state == 2'd3)) | ((sAxis_V_last_V_0_state == 2'd1) & (sAxis_V_last_V_0_ack_out == 1'b1)) | ((sAxis_V_last_V_0_state == 2'd2) & (sAxis_V_last_V_0_vld_in == 1'b1)))) begin
            sAxis_V_last_V_0_state <= 2'd3;
        end else begin
            sAxis_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_user_V_0_payload_A <= 4'd0;
    end else begin
        if ((sAxis_V_user_V_0_load_A == 1'b1)) begin
            sAxis_V_user_V_0_payload_A <= sAxis_TUSER;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_user_V_0_payload_B <= 4'd0;
    end else begin
        if ((sAxis_V_user_V_0_load_B == 1'b1)) begin
            sAxis_V_user_V_0_payload_B <= sAxis_TUSER;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((sAxis_V_user_V_0_ack_out == 1'b1) & (sAxis_V_user_V_0_vld_out == 1'b1))) begin
            sAxis_V_user_V_0_sel_rd <= ~sAxis_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((sAxis_V_user_V_0_ack_in == 1'b1) & (sAxis_V_user_V_0_vld_in == 1'b1))) begin
            sAxis_V_user_V_0_sel_wr <= ~sAxis_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sAxis_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((sAxis_V_user_V_0_state == 2'd2) & (sAxis_V_user_V_0_vld_in == 1'b0)) | ((sAxis_V_user_V_0_state == 2'd3) & (sAxis_V_user_V_0_vld_in == 1'b0) & (sAxis_V_user_V_0_ack_out == 1'b1)))) begin
            sAxis_V_user_V_0_state <= 2'd2;
        end else if ((((sAxis_V_user_V_0_state == 2'd1) & (sAxis_V_user_V_0_ack_out == 1'b0)) | ((sAxis_V_user_V_0_state == 2'd3) & (sAxis_V_user_V_0_ack_out == 1'b0) & (sAxis_V_user_V_0_vld_in == 1'b1)))) begin
            sAxis_V_user_V_0_state <= 2'd1;
        end else if (((~((sAxis_V_user_V_0_vld_in == 1'b0) & (sAxis_V_user_V_0_ack_out == 1'b1)) & ~((sAxis_V_user_V_0_ack_out == 1'b0) & (sAxis_V_user_V_0_vld_in == 1'b1)) & (sAxis_V_user_V_0_state == 2'd3)) | ((sAxis_V_user_V_0_state == 2'd1) & (sAxis_V_user_V_0_ack_out == 1'b1)) | ((sAxis_V_user_V_0_state == 2'd2) & (sAxis_V_user_V_0_vld_in == 1'b1)))) begin
            sAxis_V_user_V_0_state <= 2'd3;
        end else begin
            sAxis_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_V_45_reg_1533 <= 32'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            status_V_45_reg_1533 <= status_V_45_fu_892_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_V_49_reg_1566 <= 32'd0;
    end else begin
        if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
            status_V_49_reg_1566 <= status_V_49_fu_1216_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_323_cast_i_i_i_reg_1512 <= 10'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            tmp_323_cast_i_i_i_reg_1512 <= {{sAxis_V_data_V_0_data_out[21:12]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_379_i_i_i_reg_1578 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            tmp_379_i_i_i_reg_1578 <= tmp_379_i_i_i_fu_1348_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        wibErrCommaChar_reg_1502 <= 1'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            wibErrCommaChar_reg_1502 <= wibErrCommaChar_fu_624_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        wibErrErrors_reg_1522 <= 1'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            wibErrErrors_reg_1522 <= wibErrErrors_fu_672_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        wibErrRsvd_reg_1517 <= 1'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            wibErrRsvd_reg_1517 <= wibErrRsvd_fu_666_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        wibErrVersion_reg_1507 <= 1'd0;
    end else begin
        if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            wibErrVersion_reg_1507 <= wibErrVersion_fu_640_p2;
        end
    end
end

always @ (*) begin
    if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state11) & ((p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) | (tmp_379_i_i_i_reg_1578 == 1'd0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1423)) begin
        if ((tmp_84_fu_1442_p1 == 1'd0)) begin
            ap_phi_mux_ReadFrame_m_status_V_phi_fu_422_p6 = status_V_52_fu_1474_p3;
        end else if ((tmp_84_fu_1442_p1 == 1'd1)) begin
            ap_phi_mux_ReadFrame_m_status_V_phi_fu_422_p6 = p_Result_20_fu_1483_p4;
        end else begin
            ap_phi_mux_ReadFrame_m_status_V_phi_fu_422_p6 = ReadFrame_m_status_V_reg_419;
        end
    end else begin
        ap_phi_mux_ReadFrame_m_status_V_phi_fu_422_p6 = ReadFrame_m_status_V_reg_419;
    end
end

always @ (*) begin
    if (((tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        if ((grp_fu_441_p3 == 1'd1)) begin
            ap_phi_mux_p_Val2_32_phi_fu_412_p4 = p_Result_16_fu_1390_p4;
        end else if ((grp_fu_441_p3 == 1'd0)) begin
            ap_phi_mux_p_Val2_32_phi_fu_412_p4 = p_Val2_i2_0_i10_i_s_reg_377;
        end else begin
            ap_phi_mux_p_Val2_32_phi_fu_412_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_p_Val2_32_phi_fu_412_p4 = 'bx;
    end
end

always @ (*) begin
    if (((tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        if ((grp_fu_441_p3 == 1'd1)) begin
            ap_phi_mux_p_Val2_34_phi_fu_402_p4 = p_Result_16_fu_1390_p4;
        end else if ((grp_fu_441_p3 == 1'd0)) begin
            ap_phi_mux_p_Val2_34_phi_fu_402_p4 = p_Val2_31_reg_367;
        end else begin
            ap_phi_mux_p_Val2_34_phi_fu_402_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_p_Val2_34_phi_fu_402_p4 = 'bx;
    end
end

always @ (*) begin
    if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state11) & ((p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) | (tmp_379_i_i_i_reg_1578 == 1'd0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        frame_m_dat_d_0_address1 = newIndex_cast_i_i_i_fu_1384_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        frame_m_dat_d_0_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        frame_m_dat_d_0_address1 = newIndex10_cast_i_i_s_fu_1056_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_m_dat_d_0_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        frame_m_dat_d_0_address1 = 64'd0;
    end else begin
        frame_m_dat_d_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | (~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        frame_m_dat_d_0_ce1 = 1'b1;
    end else begin
        frame_m_dat_d_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (tmp_77_fu_1370_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((tmp_76_fu_1042_p1 == 1'd0) & (sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | (~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        frame_m_dat_d_0_we1 = 1'b1;
    end else begin
        frame_m_dat_d_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        frame_m_dat_d_1_address1 = newIndex_cast_i_i_i_fu_1384_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        frame_m_dat_d_1_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        frame_m_dat_d_1_address1 = newIndex10_cast_i_i_s_fu_1056_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        frame_m_dat_d_1_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_m_dat_d_1_address1 = 64'd0;
    end else begin
        frame_m_dat_d_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        frame_m_dat_d_1_ce1 = 1'b1;
    end else begin
        frame_m_dat_d_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_77_fu_1370_p1 == 1'd1) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((tmp_76_fu_1042_p1 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        frame_m_dat_d_1_we1 = 1'b1;
    end else begin
        frame_m_dat_d_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        iframe_assign_c_blk_n = iframe_assign_c_full_n;
    end else begin
        iframe_assign_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        iframe_assign_c_write = 1'b1;
    end else begin
        iframe_assign_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        sAxis_TDATA_blk_n = sAxis_V_data_V_0_state[1'd0];
    end else begin
        sAxis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        sAxis_V_data_V_0_ack_out = 1'b1;
    end else begin
        sAxis_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((sAxis_V_data_V_0_sel == 1'b1)) begin
        sAxis_V_data_V_0_data_out = sAxis_V_data_V_0_payload_B;
    end else begin
        sAxis_V_data_V_0_data_out = sAxis_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        sAxis_V_dest_V_0_ack_out = 1'b1;
    end else begin
        sAxis_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        sAxis_V_last_V_0_ack_out = 1'b1;
    end else begin
        sAxis_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((sAxis_V_last_V_0_sel == 1'b1)) begin
        sAxis_V_last_V_0_data_out = sAxis_V_last_V_0_payload_B;
    end else begin
        sAxis_V_last_V_0_data_out = sAxis_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if (((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        sAxis_V_user_V_0_ack_out = 1'b1;
    end else begin
        sAxis_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((sAxis_V_user_V_0_sel == 1'b1)) begin
        sAxis_V_user_V_0_data_out = sAxis_V_user_V_0_payload_B;
    end else begin
        sAxis_V_user_V_0_data_out = sAxis_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((exitcond_i_i_i_fu_1024_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((sAxis_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state11) & ((p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) | (tmp_379_i_i_i_reg_1578 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0)) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state11 = ((tmp_379_i_i_i_reg_1578 == 1'd1) & (sAxis_V_data_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((sAxis_V_data_V_0_vld_out == 1'b0) | (iframe_assign_c_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1423 = ((p_not_i_i_i_i_i_i_fu_1402_p2 == 1'd1) & (tmp_379_i_i_i_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state11));
end

assign ap_return = ap_phi_mux_ReadFrame_m_status_V_phi_fu_422_p6;

assign cdErrCvtCnt_1_fu_1180_p2 = ((grp_fu_449_p4 != ctx_cvtCnt1) ? 1'b1 : 1'b0);

assign cdErrCvtCnt_fu_856_p2 = ((grp_fu_449_p4 != ctx_cvtCnt0) ? 1'b1 : 1'b0);

assign cdErrErrReg_1_fu_1290_p2 = ((tmp_75_fu_1286_p1 != 16'd0) ? 1'b1 : 1'b0);

assign cdErrErrReg_fu_966_p2 = ((tmp_67_fu_962_p1 != 16'd0) ? 1'b1 : 1'b0);

assign cdErrHdrs_1_fu_1306_p2 = ((grp_fu_497_p4 != tmp_374_i_i_i_fu_1296_p4) ? 1'b1 : 1'b0);

assign cdErrHdrs_fu_982_p2 = ((grp_fu_497_p4 != tmp_350_i_i_i_fu_972_p4) ? 1'b1 : 1'b0);

assign cdErrStreamErr1_1_fu_1174_p2 = ((tmp_71_fu_1170_p1 != 4'd0) ? 1'b1 : 1'b0);

assign cdErrStreamErr1_fu_850_p2 = ((tmp_63_fu_846_p1 != 4'd0) ? 1'b1 : 1'b0);

assign ctx_first_load_load_fu_594_p1 = ctx_first;

assign exitcond_i_i_i_fu_1024_p2 = ((idx_0_i_i43_i_i_i_i_reg_355 == 4'd12) ? 1'b1 : 1'b0);

assign frame_m_dat_d_0_d1 = sAxis_V_data_V_0_data_out;

assign frame_m_dat_d_1_d1 = sAxis_V_data_V_0_data_out;

assign grp_fu_441_p3 = sAxis_V_user_V_0_data_out[32'd1];

assign grp_fu_449_p4 = {{sAxis_V_data_V_0_data_out[63:48]}};

assign grp_fu_459_p4 = {{sAxis_V_data_V_0_data_out[7:4]}};

assign grp_fu_469_p2 = ((grp_fu_459_p4 != 4'd0) ? 1'b1 : 1'b0);

assign grp_fu_475_p4 = {{sAxis_V_data_V_0_data_out[15:8]}};

assign grp_fu_485_p2 = ((grp_fu_475_p4 != 8'd0) ? 1'b1 : 1'b0);

assign grp_fu_491_p2 = (16'd1 + grp_fu_449_p4);

assign grp_fu_497_p4 = {{sAxis_V_data_V_0_data_out[63:32]}};

assign grp_fu_507_p4 = {{sAxis_V_data_V_0_data_out[31:16]}};

assign grp_fu_517_p2 = ((grp_fu_507_p4 != 16'd0) ? 1'b1 : 1'b0);

assign idx_1_fu_1354_p2 = (idx_0_i_i_i_i_i_i_reg_387 + 4'd1);

assign idx_fu_1030_p2 = (idx_0_i_i43_i_i_i_i_reg_355 + 4'd1);

assign iframe_assign_c_din = iframe_assign[9:0];

assign newIndex10_cast_i_i_s_fu_1056_p1 = newIndex10_i_i_i_fu_1046_p4;

assign newIndex10_i_i_i_fu_1046_p4 = {{p_sum1_i_i_i_fu_1036_p2[3:1]}};

assign newIndex_cast_i_i_i_fu_1384_p1 = newIndex_i_i_i_fu_1374_p4;

assign newIndex_i_i_i_fu_1374_p4 = {{p_sum_i_i_i_fu_1364_p2[4:1]}};

always @ (*) begin
    p_Result_10_fu_1062_p4 = p_Val2_27_reg_335;
    p_Result_10_fu_1062_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_11_fu_1088_p4 = status_V_47_fu_1072_p3;
    p_Result_11_fu_1088_p4[32'd29] = |(1'd1);
end

always @ (*) begin
    p_Result_12_fu_1130_p4 = p_Val2_19_reg_345;
    p_Result_12_fu_1130_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_13_fu_1148_p4 = status_V_48_fu_1140_p3;
    p_Result_13_fu_1148_p4[32'd29] = |(1'd1);
end

always @ (*) begin
    p_Result_14_fu_1248_p4 = status_V_49_reg_1566;
    p_Result_14_fu_1248_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_15_fu_1264_p4 = status_V_50_fu_1257_p3;
    p_Result_15_fu_1264_p4[32'd29] = |(1'd1);
end

always @ (*) begin
    p_Result_16_fu_1390_p4 = p_Val2_31_reg_367;
    p_Result_16_fu_1390_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_17_fu_1408_p4 = ap_phi_mux_p_Val2_34_phi_fu_402_p4;
    p_Result_17_fu_1408_p4[32'd29] = |(1'd1);
end

always @ (*) begin
    p_Result_18_fu_1446_p4 = ap_phi_mux_p_Val2_32_phi_fu_412_p4;
    p_Result_18_fu_1446_p4[32'd25] = |(1'd1);
end

always @ (*) begin
    p_Result_19_fu_1464_p4 = status_V_51_fu_1456_p3;
    p_Result_19_fu_1464_p4[32'd28] = |(1'd1);
end

always @ (*) begin
    p_Result_1_fu_576_p4 = p_Val2_2_fu_560_p3;
    p_Result_1_fu_576_p4[32'd24] = |(1'd1);
end

always @ (*) begin
    p_Result_20_fu_1483_p4 = status_V_52_fu_1474_p3;
    p_Result_20_fu_1483_p4[32'd30] = |(1'd1);
end

assign p_Result_2_fu_697_p5 = {{p_Val2_3_reg_1494[31:5]}, {tmp_i_i_i_fu_687_p6}};

always @ (*) begin
    p_Result_3_fu_724_p4 = p_Result_2_fu_697_p5;
    p_Result_3_fu_724_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_4_fu_742_p4 = status_V_fu_734_p3;
    p_Result_4_fu_742_p4[32'd29] = |(1'd1);
end

always @ (*) begin
    p_Result_5_fu_770_p4 = status_V_43_fu_752_p3;
    p_Result_5_fu_770_p4[32'd5] = |(wibErrTimestamp_fu_764_p2);
end

always @ (*) begin
    p_Result_6_fu_808_p4 = p_Result_5_reg_1527;
    p_Result_6_fu_808_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_7_fu_824_p4 = status_V_44_fu_817_p3;
    p_Result_7_fu_824_p4[32'd29] = |(1'd1);
end

always @ (*) begin
    p_Result_8_fu_924_p4 = status_V_45_reg_1533;
    p_Result_8_fu_924_p4[32'd27] = |(1'd1);
end

always @ (*) begin
    p_Result_9_fu_940_p4 = status_V_46_fu_933_p3;
    p_Result_9_fu_940_p4[32'd29] = |(1'd1);
end

assign p_Result_s_fu_552_p3 = {{5'd4}, {p_Val2_18_cast_i_i_fu_536_p3}};

assign p_Val2_18_cast_i_i_1_fu_544_p3 = ((grp_fu_441_p3[0:0] === 1'b1) ? 32'd0 : 32'd67108864);

assign p_Val2_18_cast_i_i_fu_536_p3 = ((grp_fu_441_p3[0:0] === 1'b1) ? 27'd0 : 27'd67108864);

assign p_Val2_2_fu_560_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_s_fu_552_p3 : p_Val2_18_cast_i_i_1_fu_544_p3);

assign p_Val2_3_fu_586_p3 = ((tmp_53_fu_568_p3[0:0] === 1'b1) ? p_Val2_2_fu_560_p3 : p_Result_1_fu_576_p4);

assign p_not_i_i_i_i_i_i_fu_1402_p2 = ((idx_0_i_i_i_i_i_i_reg_387 == 4'd11) ? 1'b1 : 1'b0);

assign p_sum1_i_i_i_fu_1036_p2 = (4'd4 + idx_0_i_i43_i_i_i_i_reg_355);

assign p_sum_i_i_i_fu_1364_p2 = ($signed(5'd18) + $signed(tmp_380_cast_i_i_i_fu_1360_p1));

assign sAxis_TREADY = sAxis_V_dest_V_0_state[1'd1];

assign sAxis_V_data_V_0_ack_in = sAxis_V_data_V_0_state[1'd1];

assign sAxis_V_data_V_0_load_A = (sAxis_V_data_V_0_state_cmp_full & ~sAxis_V_data_V_0_sel_wr);

assign sAxis_V_data_V_0_load_B = (sAxis_V_data_V_0_state_cmp_full & sAxis_V_data_V_0_sel_wr);

assign sAxis_V_data_V_0_sel = sAxis_V_data_V_0_sel_rd;

assign sAxis_V_data_V_0_state_cmp_full = ((sAxis_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign sAxis_V_data_V_0_vld_in = sAxis_TVALID;

assign sAxis_V_data_V_0_vld_out = sAxis_V_data_V_0_state[1'd0];

assign sAxis_V_dest_V_0_vld_in = sAxis_TVALID;

assign sAxis_V_last_V_0_ack_in = sAxis_V_last_V_0_state[1'd1];

assign sAxis_V_last_V_0_load_A = (sAxis_V_last_V_0_state_cmp_full & ~sAxis_V_last_V_0_sel_wr);

assign sAxis_V_last_V_0_load_B = (sAxis_V_last_V_0_state_cmp_full & sAxis_V_last_V_0_sel_wr);

assign sAxis_V_last_V_0_sel = sAxis_V_last_V_0_sel_rd;

assign sAxis_V_last_V_0_state_cmp_full = ((sAxis_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign sAxis_V_last_V_0_vld_in = sAxis_TVALID;

assign sAxis_V_last_V_0_vld_out = sAxis_V_last_V_0_state[1'd0];

assign sAxis_V_user_V_0_ack_in = sAxis_V_user_V_0_state[1'd1];

assign sAxis_V_user_V_0_load_A = (sAxis_V_user_V_0_state_cmp_full & ~sAxis_V_user_V_0_sel_wr);

assign sAxis_V_user_V_0_load_B = (sAxis_V_user_V_0_state_cmp_full & sAxis_V_user_V_0_sel_wr);

assign sAxis_V_user_V_0_sel = sAxis_V_user_V_0_sel_rd;

assign sAxis_V_user_V_0_state_cmp_full = ((sAxis_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign sAxis_V_user_V_0_vld_in = sAxis_TVALID;

assign sAxis_V_user_V_0_vld_out = sAxis_V_user_V_0_state[1'd0];

assign status_V_11_fu_834_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_7_fu_824_p4 : status_V_44_fu_817_p3);

assign status_V_16_fu_950_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_9_fu_940_p4 : status_V_46_fu_933_p3);

always @ (*) begin
    status_V_17_fu_1008_p4 = tmp_354_i_i_i_fu_998_p4;
    status_V_17_fu_1008_p4[32'd15] = |(cdErrHdrs_fu_982_p2);
end

assign status_V_21_fu_1158_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_13_fu_1148_p4 : status_V_48_fu_1140_p3);

assign status_V_26_fu_1274_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_15_fu_1264_p4 : status_V_50_fu_1257_p3);

always @ (*) begin
    status_V_27_fu_1332_p4 = tmp_378_i_i_i_fu_1322_p4;
    status_V_27_fu_1332_p4[32'd23] = |(cdErrHdrs_1_fu_1306_p2);
end

assign status_V_30_fu_1080_p3 = ((grp_fu_441_p3[0:0] === 1'b1) ? p_Result_10_fu_1062_p4 : p_Val2_19_reg_345);

assign status_V_32_fu_1098_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_11_fu_1088_p4 : status_V_47_fu_1072_p3);

assign status_V_33_fu_1106_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_11_fu_1088_p4 : status_V_30_fu_1080_p3);

assign status_V_40_fu_1418_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_17_fu_1408_p4 : ap_phi_mux_p_Val2_34_phi_fu_402_p4);

assign status_V_41_fu_1426_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_17_fu_1408_p4 : ap_phi_mux_p_Val2_32_phi_fu_412_p4);

assign status_V_43_fu_752_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? p_Result_4_fu_742_p4 : status_V_fu_734_p3);

assign status_V_44_fu_817_p3 = ((tmp_60_fu_800_p3[0:0] === 1'b1) ? p_Result_6_fu_808_p4 : p_Result_5_reg_1527);

always @ (*) begin
    status_V_45_fu_892_p4 = tmp_343_i_i_i_fu_882_p4;
    status_V_45_fu_892_p4[32'd12] = |(cdErrCvtCnt_fu_856_p2);
end

assign status_V_46_fu_933_p3 = ((tmp_64_fu_916_p3[0:0] === 1'b1) ? p_Result_8_fu_924_p4 : status_V_45_reg_1533);

assign status_V_47_fu_1072_p3 = ((grp_fu_441_p3[0:0] === 1'b1) ? p_Result_10_fu_1062_p4 : p_Val2_27_reg_335);

assign status_V_48_fu_1140_p3 = ((tmp_68_fu_1122_p3[0:0] === 1'b1) ? p_Result_12_fu_1130_p4 : p_Val2_19_reg_345);

always @ (*) begin
    status_V_49_fu_1216_p4 = tmp_367_i_i_i_fu_1206_p4;
    status_V_49_fu_1216_p4[32'd20] = |(cdErrCvtCnt_1_fu_1180_p2);
end

assign status_V_50_fu_1257_p3 = ((tmp_72_fu_1240_p3[0:0] === 1'b1) ? p_Result_14_fu_1248_p4 : status_V_49_reg_1566);

assign status_V_51_fu_1456_p3 = ((tmp_83_fu_1434_p3[0:0] === 1'b1) ? p_Result_18_fu_1446_p4 : ap_phi_mux_p_Val2_32_phi_fu_412_p4);

assign status_V_52_fu_1474_p3 = ((sAxis_V_last_V_0_data_out[0:0] === 1'b1) ? status_V_51_fu_1456_p3 : p_Result_19_fu_1464_p4);

assign status_V_fu_734_p3 = ((tmp_56_fu_716_p3[0:0] === 1'b1) ? p_Result_3_fu_724_p4 : p_Result_2_fu_697_p5);

assign tmp_320_cast_i_i_i_fu_630_p4 = {{sAxis_V_data_V_0_data_out[12:8]}};

assign tmp_327_cast_i_i_i_fu_656_p4 = {{sAxis_V_data_V_0_data_out[47:24]}};

assign tmp_331_i_i_i_fu_780_p2 = (64'd25 + sAxis_V_data_V_0_data_out);

always @ (*) begin
    tmp_341_i_i_i_fu_862_p4 = status_V_11_fu_834_p3;
    tmp_341_i_i_i_fu_862_p4[32'd8] = |(cdErrStreamErr1_fu_850_p2);
end

always @ (*) begin
    tmp_342_i_i_i_fu_872_p4 = tmp_341_i_i_i_fu_862_p4;
    tmp_342_i_i_i_fu_872_p4[32'd9] = |(grp_fu_469_p2);
end

always @ (*) begin
    tmp_343_i_i_i_fu_882_p4 = tmp_342_i_i_i_fu_872_p4;
    tmp_343_i_i_i_fu_882_p4[32'd10] = |(grp_fu_485_p2);
end

assign tmp_350_i_i_i_fu_972_p4 = {{ctx_hdrs_V_3[63:32]}};

always @ (*) begin
    tmp_353_i_i_i_fu_988_p4 = status_V_16_fu_950_p3;
    tmp_353_i_i_i_fu_988_p4[32'd13] = |(cdErrErrReg_fu_966_p2);
end

always @ (*) begin
    tmp_354_i_i_i_fu_998_p4 = tmp_353_i_i_i_fu_988_p4;
    tmp_354_i_i_i_fu_998_p4[32'd14] = |(grp_fu_517_p2);
end

always @ (*) begin
    tmp_365_i_i_i_fu_1186_p4 = status_V_21_fu_1158_p3;
    tmp_365_i_i_i_fu_1186_p4[32'd16] = |(cdErrStreamErr1_1_fu_1174_p2);
end

always @ (*) begin
    tmp_366_i_i_i_fu_1196_p4 = tmp_365_i_i_i_fu_1186_p4;
    tmp_366_i_i_i_fu_1196_p4[32'd17] = |(grp_fu_469_p2);
end

always @ (*) begin
    tmp_367_i_i_i_fu_1206_p4 = tmp_366_i_i_i_fu_1196_p4;
    tmp_367_i_i_i_fu_1206_p4[32'd18] = |(grp_fu_485_p2);
end

assign tmp_374_i_i_i_fu_1296_p4 = {{ctx_hdrs_V_5[63:32]}};

always @ (*) begin
    tmp_377_i_i_i_fu_1312_p4 = status_V_26_fu_1274_p3;
    tmp_377_i_i_i_fu_1312_p4[32'd21] = |(cdErrErrReg_1_fu_1290_p2);
end

always @ (*) begin
    tmp_378_i_i_i_fu_1322_p4 = tmp_377_i_i_i_fu_1312_p4;
    tmp_378_i_i_i_fu_1322_p4[32'd22] = |(grp_fu_517_p2);
end

assign tmp_379_i_i_i_fu_1348_p2 = ((idx_0_i_i_i_i_i_i_reg_387 < 4'd12) ? 1'b1 : 1'b0);

assign tmp_380_cast_i_i_i_fu_1360_p1 = idx_0_i_i_i_i_i_i_reg_387;

assign tmp_53_fu_568_p3 = sAxis_V_user_V_0_data_out[32'd3];

assign tmp_55_fu_620_p1 = sAxis_V_data_V_0_data_out[7:0];

assign tmp_56_fu_716_p3 = sAxis_V_user_V_0_data_out[32'd1];

assign tmp_60_fu_800_p3 = sAxis_V_user_V_0_data_out[32'd1];

assign tmp_63_fu_846_p1 = sAxis_V_data_V_0_data_out[3:0];

assign tmp_64_fu_916_p3 = sAxis_V_user_V_0_data_out[32'd1];

assign tmp_67_fu_962_p1 = sAxis_V_data_V_0_data_out[15:0];

assign tmp_68_fu_1122_p3 = sAxis_V_user_V_0_data_out[32'd1];

assign tmp_71_fu_1170_p1 = sAxis_V_data_V_0_data_out[3:0];

assign tmp_72_fu_1240_p3 = sAxis_V_user_V_0_data_out[32'd1];

assign tmp_75_fu_1286_p1 = sAxis_V_data_V_0_data_out[15:0];

assign tmp_76_fu_1042_p1 = idx_0_i_i43_i_i_i_i_reg_355[0:0];

assign tmp_77_fu_1370_p1 = idx_0_i_i_i_i_i_i_reg_387[0:0];

assign tmp_83_fu_1434_p3 = sAxis_V_user_V_0_data_out[32'd2];

assign tmp_84_fu_1442_p1 = sAxis_V_user_V_0_data_out[0:0];

assign tmp_i_i_i_fu_687_p6 = {{{{{wibErrErrors_reg_1522}, {wibErrRsvd_reg_1517}}, {wibErrId_fu_682_p2}}, {wibErrVersion_reg_1507}}, {wibErrCommaChar_reg_1502}};

assign wibErrCommaChar_fu_624_p2 = ((tmp_55_fu_620_p1 != 8'd188) ? 1'b1 : 1'b0);

assign wibErrErrors_fu_672_p2 = ((grp_fu_449_p4 != 16'd0) ? 1'b1 : 1'b0);

assign wibErrId_fu_682_p2 = ((tmp_323_cast_i_i_i_reg_1512 != ctx_wibId_V) ? 1'b1 : 1'b0);

assign wibErrRsvd_fu_666_p2 = ((tmp_327_cast_i_i_i_fu_656_p4 != 24'd0) ? 1'b1 : 1'b0);

assign wibErrTimestamp_fu_764_p2 = ((sAxis_V_data_V_0_data_out != ctx_hdrs_V_1) ? 1'b1 : 1'b0);

assign wibErrVersion_fu_640_p2 = ((tmp_320_cast_i_i_i_fu_630_p4 != 5'd1) ? 1'b1 : 1'b0);

endmodule //read196
