// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// BUS_A
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of cfg
//        bit 31~0 - cfg[31:0] (Read/Write)
// 0x14 : Data signal of cfg
//        bit 31~0 - cfg[63:32] (Read/Write)
// 0x18 : Data signal of cfg
//        bit 31~0 - cfg[95:64] (Read/Write)
// 0x1c : Data signal of cfg
//        bit 31~0 - cfg[127:96] (Read/Write)
// 0x20 : Data signal of cfg
//        bit 31~0 - cfg[159:128] (Read/Write)
// 0x24 : Data signal of cfg
//        bit 31~0 - cfg[191:160] (Read/Write)
// 0x28 : Data signal of cfg
//        bit 31~0 - cfg[223:192] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of monitor_common_pattern
//        bit 31~0 - monitor_common_pattern[31:0] (Read)
// 0x34 : Control signal of monitor_common_pattern
//        bit 0  - monitor_common_pattern_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of monitor_cfg
//        bit 31~0 - monitor_cfg[31:0] (Read)
// 0x3c : Data signal of monitor_cfg
//        bit 31~0 - monitor_cfg[63:32] (Read)
// 0x40 : Control signal of monitor_cfg
//        bit 0  - monitor_cfg_ap_vld (Read/COR)
//        others - reserved
// 0x44 : Data signal of monitor_read
//        bit 31~0 - monitor_read[31:0] (Read)
// 0x48 : Data signal of monitor_read
//        bit 31~0 - monitor_read[63:32] (Read)
// 0x4c : Data signal of monitor_read
//        bit 31~0 - monitor_read[95:64] (Read)
// 0x50 : Data signal of monitor_read
//        bit 31~0 - monitor_read[127:96] (Read)
// 0x54 : Data signal of monitor_read
//        bit 31~0 - monitor_read[159:128] (Read)
// 0x58 : Data signal of monitor_read
//        bit 31~0 - monitor_read[191:160] (Read)
// 0x5c : Data signal of monitor_read
//        bit 31~0 - monitor_read[223:192] (Read)
// 0x60 : Data signal of monitor_read
//        bit 31~0 - monitor_read[255:224] (Read)
// 0x64 : Data signal of monitor_read
//        bit 31~0 - monitor_read[287:256] (Read)
// 0x68 : Data signal of monitor_read
//        bit 31~0 - monitor_read[319:288] (Read)
// 0x6c : Data signal of monitor_read
//        bit 31~0 - monitor_read[351:320] (Read)
// 0x70 : Data signal of monitor_read
//        bit 31~0 - monitor_read[383:352] (Read)
// 0x74 : Data signal of monitor_read
//        bit 31~0 - monitor_read[415:384] (Read)
// 0x78 : Data signal of monitor_read
//        bit 31~0 - monitor_read[447:416] (Read)
// 0x7c : Data signal of monitor_read
//        bit 31~0 - monitor_read[479:448] (Read)
// 0x80 : Data signal of monitor_read
//        bit 31~0 - monitor_read[511:480] (Read)
// 0x84 : Data signal of monitor_read
//        bit 31~0 - monitor_read[543:512] (Read)
// 0x88 : Data signal of monitor_read
//        bit 31~0 - monitor_read[575:544] (Read)
// 0x8c : Data signal of monitor_read
//        bit 31~0 - monitor_read[607:576] (Read)
// 0x90 : Data signal of monitor_read
//        bit 31~0 - monitor_read[639:608] (Read)
// 0x94 : Data signal of monitor_read
//        bit 31~0 - monitor_read[671:640] (Read)
// 0x98 : Data signal of monitor_read
//        bit 31~0 - monitor_read[703:672] (Read)
// 0x9c : Data signal of monitor_read
//        bit 31~0 - monitor_read[735:704] (Read)
// 0xa0 : Data signal of monitor_read
//        bit 31~0 - monitor_read[767:736] (Read)
// 0xa4 : Data signal of monitor_read
//        bit 31~0 - monitor_read[799:768] (Read)
// 0xa8 : Data signal of monitor_read
//        bit 31~0 - monitor_read[831:800] (Read)
// 0xac : Data signal of monitor_read
//        bit 31~0 - monitor_read[863:832] (Read)
// 0xb0 : Data signal of monitor_read
//        bit 31~0 - monitor_read[895:864] (Read)
// 0xb4 : Data signal of monitor_read
//        bit 31~0 - monitor_read[927:896] (Read)
// 0xb8 : Data signal of monitor_read
//        bit 31~0 - monitor_read[959:928] (Read)
// 0xbc : Data signal of monitor_read
//        bit 31~0 - monitor_read[991:960] (Read)
// 0xc0 : Data signal of monitor_read
//        bit 31~0 - monitor_read[1023:992] (Read)
// 0xc4 : Data signal of monitor_read
//        bit 31~0 - monitor_read[1055:1024] (Read)
// 0xc8 : Data signal of monitor_read
//        bit 31~0 - monitor_read[1087:1056] (Read)
// 0xcc : Data signal of monitor_read
//        bit 31~0 - monitor_read[1119:1088] (Read)
// 0xd0 : Control signal of monitor_read
//        bit 0  - monitor_read_ap_vld (Read/COR)
//        others - reserved
// 0xd4 : Data signal of monitor_write
//        bit 31~0 - monitor_write[31:0] (Read)
// 0xd8 : Data signal of monitor_write
//        bit 31~0 - monitor_write[63:32] (Read)
// 0xdc : Data signal of monitor_write
//        bit 31~0 - monitor_write[95:64] (Read)
// 0xe0 : Data signal of monitor_write
//        bit 31~0 - monitor_write[127:96] (Read)
// 0xe4 : Control signal of monitor_write
//        bit 0  - monitor_write_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_AP_CTRL                     0x00
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_GIE                         0x04
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_IER                         0x08
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_ISR                         0x0c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_CFG_DATA                    0x10
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_CFG_DATA                    224
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_COMMON_PATTERN_DATA 0x30
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_COMMON_PATTERN_DATA 32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_COMMON_PATTERN_CTRL 0x34
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_CFG_DATA            0x38
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_CFG_DATA            64
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_CFG_CTRL            0x40
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_DATA           0x44
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_READ_DATA           1120
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_DATA_          0x6c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_READ_DATA           1120
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_CTRL           0xd0
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_DATA          0xd4
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_WRITE_DATA          128
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_CTRL          0xe4

