// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// BUS_A
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x010 : Data signal of cfg_init
//         bit 31~0 - cfg_init[31:0] (Read/Write)
// 0x014 : reserved
// 0x018 : Data signal of cfg_mode
//         bit 31~0 - cfg_mode[31:0] (Read/Write)
// 0x01c : reserved
// 0x020 : Data signal of cfg_limit
//         bit 31~0 - cfg_limit[31:0] (Read/Write)
// 0x024 : reserved
// 0x100 : Data signal of monitor_common_pattern
//         bit 31~0 - monitor_common_pattern[31:0] (Read)
// 0x104 : Control signal of monitor_common_pattern
//         bit 0  - monitor_common_pattern_ap_vld (Read/COR)
//         others - reserved
// 0x108 : Data signal of monitor_cfg_m_mode
//         bit 31~0 - monitor_cfg_m_mode[31:0] (Read)
// 0x10c : Control signal of monitor_cfg_m_mode
//         bit 0  - monitor_cfg_m_mode_ap_vld (Read/COR)
//         others - reserved
// 0x110 : Data signal of monitor_cfg_m_ncfgs
//         bit 31~0 - monitor_cfg_m_ncfgs[31:0] (Read)
// 0x114 : Control signal of monitor_cfg_m_ncfgs
//         bit 0  - monitor_cfg_m_ncfgs_ap_vld (Read/COR)
//         others - reserved
// 0x118 : Data signal of monitor_read_summary_mask_V
//         bit 31~0 - monitor_read_summary_mask_V[31:0] (Read)
// 0x11c : Control signal of monitor_read_summary_mask_V
//         bit 0  - monitor_read_summary_mask_V_ap_vld (Read/COR)
//         others - reserved
// 0x120 : Data signal of monitor_read_summary_nframes
//         bit 31~0 - monitor_read_summary_nframes[31:0] (Read)
// 0x124 : Control signal of monitor_read_summary_nframes
//         bit 0  - monitor_read_summary_nframes_ap_vld (Read/COR)
//         others - reserved
// 0x200 : Data signal of monitor_write_nbytes
//         bit 31~0 - monitor_write_nbytes[31:0] (Read)
// 0x204 : Control signal of monitor_write_nbytes
//         bit 0  - monitor_write_nbytes_ap_vld (Read/COR)
//         others - reserved
// 0x208 : Data signal of monitor_write_npromoted
//         bit 31~0 - monitor_write_npromoted[31:0] (Read)
// 0x20c : Control signal of monitor_write_npromoted
//         bit 0  - monitor_write_npromoted_ap_vld (Read/COR)
//         others - reserved
// 0x210 : Data signal of monitor_write_ndropped
//         bit 31~0 - monitor_write_ndropped[31:0] (Read)
// 0x214 : Control signal of monitor_write_ndropped
//         bit 0  - monitor_write_ndropped_ap_vld (Read/COR)
//         others - reserved
// 0x218 : Data signal of monitor_write_npackets
//         bit 31~0 - monitor_write_npackets[31:0] (Read)
// 0x21c : Control signal of monitor_write_npackets
//         bit 0  - monitor_write_npackets_ap_vld (Read/COR)
//         others - reserved
// 0x080 ~
// 0x0ff : Memory 'cfg_chns_disabled' (128 * 1b)
//         Word n : bit [ 0: 0] - cfg_chns_disabled[4n]
//                  bit [ 8: 8] - cfg_chns_disabled[4n+1]
//                  bit [16:16] - cfg_chns_disabled[4n+2]
//                  bit [24:24] - cfg_chns_disabled[4n+3]
//                  others      - reserved
// 0x130 ~
// 0x13f : Memory 'monitor_read_summary_nStates' (4 * 32b)
//         Word n : bit [31:0] - monitor_read_summary_nStates[n]
// 0x140 ~
// 0x15f : Memory 'monitor_read_errs_nFrameErrs' (5 * 32b)
//         Word n : bit [31:0] - monitor_read_errs_nFrameErrs[n]
// 0x180 ~
// 0x1ff : Memory 'monitor_read_errs_nWibErrs' (24 * 32b)
//         Word n : bit [31:0] - monitor_read_errs_nWibErrs[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_AP_CTRL                           0x000
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_GIE                               0x004
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_IER                               0x008
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_ISR                               0x00c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_CFG_INIT_DATA                     0x010
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_CFG_INIT_DATA                     32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_CFG_MODE_DATA                     0x018
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_CFG_MODE_DATA                     32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_CFG_LIMIT_DATA                    0x020
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_CFG_LIMIT_DATA                    32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_COMMON_PATTERN_DATA       0x100
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_COMMON_PATTERN_DATA       32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_COMMON_PATTERN_CTRL       0x104
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_CFG_M_MODE_DATA           0x108
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_CFG_M_MODE_DATA           32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_CFG_M_MODE_CTRL           0x10c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_CFG_M_NCFGS_DATA          0x110
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_CFG_M_NCFGS_DATA          32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_CFG_M_NCFGS_CTRL          0x114
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_SUMMARY_MASK_V_DATA  0x118
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_READ_SUMMARY_MASK_V_DATA  32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_SUMMARY_MASK_V_CTRL  0x11c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_SUMMARY_NFRAMES_DATA 0x120
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_READ_SUMMARY_NFRAMES_DATA 32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_SUMMARY_NFRAMES_CTRL 0x124
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NBYTES_DATA         0x200
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_WRITE_NBYTES_DATA         32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NBYTES_CTRL         0x204
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NPROMOTED_DATA      0x208
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_WRITE_NPROMOTED_DATA      32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NPROMOTED_CTRL      0x20c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NDROPPED_DATA       0x210
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_WRITE_NDROPPED_DATA       32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NDROPPED_CTRL       0x214
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NPACKETS_DATA       0x218
#define XDUNEDATACOMPRESSIONCORE_BUS_A_BITS_MONITOR_WRITE_NPACKETS_DATA       32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_WRITE_NPACKETS_CTRL       0x21c
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_CFG_CHNS_DISABLED_BASE            0x080
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_CFG_CHNS_DISABLED_HIGH            0x0ff
#define XDUNEDATACOMPRESSIONCORE_BUS_A_WIDTH_CFG_CHNS_DISABLED                1
#define XDUNEDATACOMPRESSIONCORE_BUS_A_DEPTH_CFG_CHNS_DISABLED                128
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_SUMMARY_NSTATES_BASE 0x130
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_SUMMARY_NSTATES_HIGH 0x13f
#define XDUNEDATACOMPRESSIONCORE_BUS_A_WIDTH_MONITOR_READ_SUMMARY_NSTATES     32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_DEPTH_MONITOR_READ_SUMMARY_NSTATES     4
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_ERRS_NFRAMEERRS_BASE 0x140
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_ERRS_NFRAMEERRS_HIGH 0x15f
#define XDUNEDATACOMPRESSIONCORE_BUS_A_WIDTH_MONITOR_READ_ERRS_NFRAMEERRS     32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_DEPTH_MONITOR_READ_ERRS_NFRAMEERRS     5
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_ERRS_NWIBERRS_BASE   0x180
#define XDUNEDATACOMPRESSIONCORE_BUS_A_ADDR_MONITOR_READ_ERRS_NWIBERRS_HIGH   0x1ff
#define XDUNEDATACOMPRESSIONCORE_BUS_A_WIDTH_MONITOR_READ_ERRS_NWIBERRS       32
#define XDUNEDATACOMPRESSIONCORE_BUS_A_DEPTH_MONITOR_READ_ERRS_NWIBERRS       24

